#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Regenerates shz_wupper.h: the simple (1:1) Unicode upper-case mapping of the Basic Multilingual Plane, taken from
Python's unicodedata (Unicode database of the running interpreter), as compact runs. The Shizuku system DLLs have no
NLS tables, so this is what "case-insensitive" means to them: two UTF-16 code units are equal ignoring case when their
simple upper-case mappings are equal. Usage: python3 gen_wupper.py > shz_wupper.h
"""
import sys
import unicodedata


def main():
    m = {}
    for cp in range(0x10000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        u = chr(cp).upper()
        if len(u) == 1 and ord(u) < 0x10000 and u != chr(cp):
            m[cp] = ord(u) - cp
    runs = []
    cps = sorted(m)
    i = 0
    while i < len(cps):
        lo, d = cps[i], m[cps[i]]
        step = 1
        # stride 2 (alternating upper/lower pairs) if the next mapped cp is lo+2 with the same delta
        if i + 1 < len(cps) and cps[i + 1] == lo + 2 and m[cps[i + 1]] == d:
            step = 2
        hi = lo
        j = i + 1
        while j < len(cps) and cps[j] == hi + step and m[cps[j]] == d:
            hi = cps[j]
            j += 1
        runs.append((lo, hi, d, step))
        i = j
    out = []
    out.append("/* SPDX-License-Identifier: GPL-2.0-only")
    out.append(" * GENERATED by gen_wupper.py from Unicode %s (Python unicodedata). Do not edit." % unicodedata.unidata_version)
    out.append(" * Simple upper-case mapping of the BMP as runs {first, last, delta, step}: code unit c in [first, last] with")
    out.append(" * (c - first) % step == 0 maps to c + delta. Used for the case-insensitive comparisons of the system DLLs. */")
    out.append("#ifndef SHZ_WUPPER_H")
    out.append("#define SHZ_WUPPER_H")
    out.append("#include <stdint.h>")
    out.append("static const struct { uint16_t lo, hi; int32_t delta; uint8_t step; } shz_upper_runs[] = {")
    for lo, hi, d, step in runs:
        out.append("    { 0x%04x, 0x%04x, %d, %d }," % (lo, hi, d, step))
    out.append("};")
    out.append("#define SHZ_UPPER_RUNS %d" % len(runs))
    out.append("""
static inline uint16_t shz_wupper(uint16_t c)
{
    unsigned lo = 0, hi = SHZ_UPPER_RUNS;
    if (c < 0x61) return c;
    if (c <= 0x7a) return (uint16_t)(c - 0x20);
    if (c < 0xb5) return c;
    while (lo < hi) {                       /* last run whose first <= c */
        unsigned mid = (lo + hi) / 2;
        if (shz_upper_runs[mid].lo <= c) lo = mid + 1; else hi = mid;
    }
    if (lo) {
        unsigned k = lo - 1;
        if (c <= shz_upper_runs[k].hi && (unsigned)(c - shz_upper_runs[k].lo) % shz_upper_runs[k].step == 0)
            return (uint16_t)(c + shz_upper_runs[k].delta);
    }
    return c;
}
#endif""")
    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write("%d mapped code points in %d runs (Unicode %s)\n" % (len(m), len(runs), unicodedata.unidata_version))


if __name__ == "__main__":
    main()
