/* SPDX-License-Identifier: GPL-2.0-only
 * Compile the selected production bodies unchanged. Independent exact rational
 * and Python Decimal expectations are generated by test_decimal_host.py. */
#define SHZ_DECIMAL_HOST
#include "../dlls/oleaut32/decimal_wine.c"
#include "../dlls/oleaut32/decimal_string_wine.c"
#include "oracle_vectors.inc"

static unsigned checks;
#define CHECK(x) do { ++checks; if (!(x)) { fprintf(stderr,"FAIL line %d: %s\n",__LINE__,#x); exit(2); } } while (0)
static _Thread_local DWORD last_error;
static _Thread_local int locale_fail, format_fail, alloc_fail, bstr_live, format_calls;
DWORD GetLastError(void) { return last_error; }
size_t host_wcslen(const WCHAR *s) { size_t n=0; while(s[n]) ++n; return n; }
int lstrlenW(const WCHAR *s) { return (int)host_wcslen(s); }
WCHAR *host_wcschr(const WCHAR *s,WCHAR c) { for (;*s;s++) if(*s==c) return (WCHAR *)s; return c?NULL:(WCHAR *)s; }
WCHAR *host_wcscpy(WCHAR *d,const WCHAR *s) { WCHAR *r=d; do { *d++=*s; } while(*s++); return r; }
WCHAR *host_wcscat(WCHAR *d,const WCHAR *s) { host_wcscpy(d+host_wcslen(d),s); return d; }
int host_wcsncmp(const WCHAR *a,const WCHAR *b,size_t n) { while(n--) { if(*a!=*b) return *a-*b; if(!*a) return 0; ++a; ++b; } return 0; }
int host_iswspace(unsigned int c) { return c==' ' || (c>=9 && c<=13) || c==0xa0; }
BSTR SysAllocString(const OLECHAR *s)
{
    size_t bytes=host_wcslen(s)*2;
    BYTE *p;
    if (alloc_fail) return NULL;
    p=malloc(bytes+6); if(!p) return NULL;
    *(DWORD *)p=(DWORD)bytes;
    memcpy(p+4,s,bytes+2); ++bstr_live;
    return (BSTR)(p+4);
}
void SysFreeString(BSTR s) { if(s) { --bstr_live; free((BYTE *)s-4); } }
int GetLocaleInfoW(LCID id,LCTYPE type,WCHAR *out,int count)
{
    const WCHAR *value=NULL;
    DWORD base=type&~(LOCALE_NOUSEROVERRIDE|LOCALE_RETURN_NUMBER);
    if(locale_fail || (id!=0x409 && id!=0x7f && id!=0x400 && id!=0x800)) { last_error=locale_fail?ERROR_ACCESS_DENIED:ERROR_INVALID_PARAMETER; return 0; }
    switch(base) {
    case LOCALE_SNEGATIVESIGN: value=(const WCHAR *)L"-"; break;
    case LOCALE_SPOSITIVESIGN: value=(const WCHAR *)L""; break;
    case LOCALE_SDECIMAL: case LOCALE_SMONDECIMALSEP: value=(const WCHAR *)L"."; break;
    case LOCALE_STHOUSAND: case LOCALE_SMONTHOUSANDSEP: value=(const WCHAR *)L","; break;
    case LOCALE_SCURRENCY: value=(const WCHAR *)(id==0x7f?L"\x00a4":L"$"); break;
    case LOCALE_ILZERO:
        if(type&LOCALE_RETURN_NUMBER) { if(count<2) goto small; *(DWORD *)out=1; return 2; }
        value=(const WCHAR *)L"1"; break;
    default: last_error=ERROR_INVALID_PARAMETER; return 0;
    }
    if(count<(int)host_wcslen(value)+1) goto small;
    host_wcscpy(out,value); return (int)host_wcslen(value)+1;
small: last_error=ERROR_INSUFFICIENT_BUFFER; return 0;
}
int GetNumberFormatW(LCID id,DWORD flags,const WCHAR *in,const NUMBERFMTW *fmt,WCHAR *out,int count)
{
    const WCHAR prefix[]=L"provider:";
    size_t n=host_wcslen(in)+host_wcslen(prefix)+1;
    (void)flags; (void)fmt; ++format_calls;
    if(format_fail || id!=0x409) {last_error=ERROR_ACCESS_DENIED; return 0;}
    if(count<(int)n) {last_error=ERROR_INSUFFICIENT_BUFFER; return 0;}
    host_wcscpy(out,prefix); host_wcscat(out,in); return (int)n;
}
static DECIMAL dec(ULONG64 lo,DWORD hi,BYTE scale,BYTE sign)
{
    DECIMAL d={0}; d.Lo64=lo; d.Hi32=hi; d.scale=scale; d.sign=sign; return d;
}
static int equal(DECIMAL a,DECIMAL b)
{
    unsigned __int128 ma=((unsigned __int128)a.Hi32<<64)|a.Lo64;
    unsigned __int128 mb=((unsigned __int128)b.Hi32<<64)|b.Lo64;
    while(a.scale && ma%10==0) {--a.scale;ma/=10;}
    while(b.scale && mb%10==0) {--b.scale;mb/=10;}
    return ma==mb && ((!ma && !mb) || (a.sign==b.sign && a.scale==b.scale));
}
static void integer_oracle(void)
{
    size_t i;
    for(i=0;i<sizeof(int_vectors)/sizeof(int_vectors[0]);i++) {
        const struct int_vector *v=&int_vectors[i];
        DECIMAL d=v->input, saved=d; LONG64 signed_value=123; ULONG64 unsigned_value=123;
        HRESULT hr=VarI8FromDec(&d,&signed_value);
        CHECK(hr==v->signed_hr); CHECK(hr!=S_OK || signed_value==v->signed_value);
        CHECK(hr==S_OK || signed_value==123);
        hr=VarUI8FromDec(&d,&unsigned_value);
        CHECK(hr==v->unsigned_hr); CHECK(hr!=S_OK || unsigned_value==v->unsigned_value);
        CHECK(hr==S_OK || unsigned_value==123); CHECK(!memcmp(&d,&saved,sizeof d));
        if(v->signed_hr==S_OK) {
            SHORT s=123; LONG l=123; BYTE b=123; USHORT u=123; ULONG ul=123;
            CHECK(VarI2FromDec(&d,&s)==((v->signed_value>=-32768 && v->signed_value<=32767)?S_OK:DISP_E_OVERFLOW));
            CHECK(VarI4FromDec(&d,&l)==((v->signed_value>=INT32_MIN && v->signed_value<=INT32_MAX)?S_OK:DISP_E_OVERFLOW));
            CHECK(VarUI1FromDec(&d,&b)==((v->signed_value>=0 && v->signed_value<=255)?S_OK:DISP_E_OVERFLOW));
            CHECK(VarUI2FromDec(&d,&u)==((v->signed_value>=0 && v->signed_value<=65535)?S_OK:DISP_E_OVERFLOW));
            CHECK(VarUI4FromDec(&d,&ul)==((v->signed_value>=0 && v->signed_value<=UINT32_MAX)?S_OK:DISP_E_OVERFLOW));
        }
    }
}
static void arithmetic_oracle(void)
{
    size_t i; HRESULT (*ops[])(DECIMAL *,DECIMAL *,DECIMAL *)={VarDecAdd,VarDecSub,VarDecMul,VarDecDiv};
    for(i=0;i<sizeof(math_vectors)/sizeof(math_vectors[0]);i++) {
        const struct math_vector *v=&math_vectors[i]; DECIMAL a=v->a,b=v->b,out={0},aa=a,bb=b;
        HRESULT hr=ops[v->op](&a,&b,&out);
        if(hr!=v->hr || (hr==S_OK && !equal(out,v->expected))) {
            fprintf(stderr,"math vector %zu op %u hr %08x input %llu/%u %llu/%u out %u:%llu/%u expected %u:%llu/%u\n",i,v->op,(unsigned)hr,(unsigned long long)a.Lo64,a.scale,(unsigned long long)b.Lo64,b.scale,out.Hi32,(unsigned long long)out.Lo64,out.scale,v->expected.Hi32,(unsigned long long)v->expected.Lo64,v->expected.scale);
            exit(2);
        }
        CHECK(1); CHECK(!memcmp(&a,&aa,sizeof a)&&!memcmp(&b,&bb,sizeof b));
        CHECK(out.scale<=28 && !(out.sign&~DECIMAL_NEG) && out.wReserved==0);
        if(hr==S_OK) {
            CHECK(ops[v->op](&a,&b,&a)==S_OK && equal(a,v->expected));
            a=aa; CHECK(ops[v->op](&a,&b,&b)==S_OK && equal(b,v->expected));
        }
    }
}
static void contract_edges(void)
{
    DECIMAL d=dec(1,0,0,0), out, bad=dec(0,0,29,0), max=dec(UINT64_MAX,UINT32_MAX,0,0), one=d;
    LONG64 n; ULONG64 un; LONG l; float f; double dbl; BYTE byte; USHORT us; ULONG ul; SHORT s; BSTR b;
    CHECK(VarI8FromDec(&bad,&n)==E_INVALIDARG && VarUI8FromDec(&bad,&un)==E_INVALIDARG);
    bad.scale=0; bad.sign=1;
    CHECK(VarDecAdd(&bad,&d,&out)==E_INVALIDARG && VarDecDiv(&d,&bad,&out)==E_INVALIDARG);
    CHECK(VarDecNeg(NULL,&out)==E_INVALIDARG && VarDecCmp(NULL,&d)==E_INVALIDARG);
    CHECK(VarDecFromUI1(0,NULL)==E_INVALIDARG && VarDecFromUI2(0,NULL)==E_INVALIDARG && VarDecFromUI4(0,NULL)==E_INVALIDARG);
    CHECK(VarDecFromI2(0,NULL)==E_INVALIDARG && VarDecFromI4(0,NULL)==E_INVALIDARG && VarDecFromI8(0,NULL)==E_INVALIDARG && VarDecFromUI8(0,NULL)==E_INVALIDARG);
    CHECK(VarR4FromDec(&bad,&f)==E_INVALIDARG && VarR8FromDec(&bad,&dbl)==E_INVALIDARG);
    CHECK(VarBstrFromDec(&bad,0x409,0,&b)==E_INVALIDARG);
    CHECK(VarI2FromDec(NULL,&s)==E_INVALIDARG && VarI4FromDec(NULL,&l)==E_INVALIDARG && VarUI1FromDec(NULL,&byte)==E_INVALIDARG && VarUI2FromDec(NULL,&us)==E_INVALIDARG && VarUI4FromDec(NULL,&ul)==E_INVALIDARG);
    CHECK(VarDecFromI4(INT32_MIN,&out)==S_OK && out.sign==0x80 && out.Lo64==2147483648ULL && !out.Hi32 && !out.scale);
    CHECK(VarDecFromI8(INT64_MIN,&out)==S_OK && out.Lo64==0x8000000000000000ULL && out.sign==0x80 && VarI8FromDec(&out,&n)==S_OK && n==INT64_MIN);
    CHECK(VarDecFromUI8(UINT64_MAX,&out)==S_OK && out.Lo64==UINT64_MAX && VarUI8FromDec(&out,&un)==S_OK && un==UINT64_MAX);
    CHECK(VarDecFromUI1(255,&out)==S_OK && out.Lo64==255);
    CHECK(VarDecFromI2(-32768,&out)==S_OK && out.Lo64==32768 && out.sign==0x80);
    CHECK(VarDecFromUI2(65535,&out)==S_OK && out.Lo64==65535);
    CHECK(VarDecFromUI4(UINT32_MAX,&out)==S_OK && out.Lo64==UINT32_MAX);
    CHECK(VarDecAdd(&max,&one,&out)==DISP_E_OVERFLOW);
    d.Lo64=0; CHECK(VarDecDiv(&one,&d,&out)==DISP_E_DIVBYZERO);
    CHECK(VarDecNeg(&one,&one)==S_OK && one.sign==0x80);
    CHECK(VarDecCmp(&one,&d)==VARCMP_LT && VarDecCmp(&d,&d)==VARCMP_EQ && VarDecCmp(&max,&d)==VARCMP_GT);
    CHECK(VarDecFromR8(INFINITY,&out)==DISP_E_OVERFLOW && VarDecFromR8(NAN,&out)==DISP_E_BADVARTYPE);
    CHECK(VarDecFromR4(INFINITY,&out)==DISP_E_OVERFLOW && VarDecFromR4(NAN,&out)==DISP_E_BADVARTYPE);
    CHECK(VarDecFromR8(0.5,&out)==S_OK && equal(out,dec(5,0,1,0)));
    CHECK(VarDecFromR4(-0.5f,&out)==S_OK && equal(out,dec(5,0,1,0x80)));
    CHECK(VarDecFromR8(0x1p-1074,&out)==S_OK && !out.Hi32 && !out.Lo64);
    CHECK(VarDecFromR4(0x1p-149f,&out)==S_OK && !out.Hi32 && !out.Lo64);
    d=dec(5,0,1,0); CHECK(VarR8FromDec(&d,&dbl)==S_OK && dbl==0.5 && VarR4FromDec(&d,&f)==S_OK && f==0.5f);
    d.sign=0x80; CHECK(VarR8FromDec(&d,&dbl)==S_OK && dbl==-0.5);
    {
        uint64_t random=0x01a0f3d0cb43ULL; unsigned i;
        for(i=0;i<512;i++) {
            union {uint64_t bits; double value;} value;
            random=random*6364136223846793005ULL+1442695040888963407ULL;
            /* Finite normal exponents whose values fit DECIMAL with >14 significant digits. */
            value.bits=(random&0x800fffffffffffffULL)|((uint64_t)(990+i%120)<<52);
            CHECK(VarDecFromR8(value.value,&out)==S_OK && out.scale<=28 && !out.wReserved);
            CHECK(VarR8FromDec(&out,&dbl)==S_OK && fabs(dbl-value.value)<=fabs(value.value)*1e-14+1e-28);
            f=(float)value.value;
            CHECK(VarDecFromR4(f,&out)==S_OK && out.scale<=28 && !out.wReserved);
            CHECK(VarR4FromDec(&out,&f)==S_OK && fabs((double)f-(double)(float)value.value)<=fabs((double)(float)value.value)*1e-6+1e-28);
        }
    }
}
static void string_edges(void)
{
    DECIMAL d=dec(12345,0,2,0),out={0},saved; ULONG ui=123; BSTR b=(BSTR)(uintptr_t)1;
    size_t i;
    for(i=0;i<sizeof(string_vectors)/sizeof(string_vectors[0]);i++) {
        const struct string_vector *v=&string_vectors[i];
        HRESULT hr=VarDecFromStr(v->source,0x409,0,&out);
        if(hr!=v->hr || (hr==S_OK && !equal(out,v->expected))) {
            fprintf(stderr,"parse vector %zu hr %08x expected %08x out %u:%llu/%u expected %u:%llu/%u\n",i,(unsigned)hr,(unsigned)v->hr,out.Hi32,(unsigned long long)out.Lo64,out.scale,v->expected.Hi32,(unsigned long long)v->expected.Lo64,v->expected.scale);
            exit(2);
        }
        CHECK(1); CHECK(hr!=S_OK || (out.scale<=28 && !out.wReserved));
    }
    CHECK(VarDecFromStr((const WCHAR *)L"18446744073709551616",0x409,0,&out)==S_OK && out.Hi32==1 && out.Lo64==0);
    CHECK(VarDecFromStr((const WCHAR *)L" -1.25e2 ",0x409,0,&out)==S_OK && equal(out,dec(125,0,0,0x80)));
    CHECK(VarDecFromStr((const WCHAR *)L"($1,234.5)",0x409,0,&out)==S_OK && equal(out,dec(12345,0,1,0x80)));
    CHECK(VarDecFromStr(NULL,0x409,0,&out)==DISP_E_TYPEMISMATCH);
    CHECK(VarDecFromStr((const WCHAR *)L"abc",0x409,0,&out)==DISP_E_TYPEMISMATCH);
    CHECK(VarDecFromStr((const WCHAR *)L"1e-256",0x409,0,&out)==S_OK && !out.Lo64 && !out.Hi32 && out.scale<=28);
    CHECK(VarDecFromStr((const WCHAR *)L"1e214748364800000",0x409,0,&out)==DISP_E_OVERFLOW);
    CHECK(VarDecFromStr((const WCHAR *)L"1e-214748364800000",0x409,0,&out)==S_OK && !out.Lo64 && !out.Hi32 && out.scale<=28);
    CHECK(VarUI4FromStr((const WCHAR *)L"1e214748364800000",0x409,0,&ui)==DISP_E_OVERFLOW);
    CHECK(VarUI4FromStr((const WCHAR *)L"1e-214748364800000",0x409,0,&ui)==S_OK && !ui);
    CHECK(VarDecFromStr((const WCHAR *)L"79228162514264337593543950336",0x409,0,&out)==DISP_E_OVERFLOW);
    CHECK(VarUI4FromStr((const WCHAR *)L"4294967295",0x409,0,&ui)==S_OK && ui==UINT32_MAX);
    CHECK(VarUI4FromStr((const WCHAR *)L"4294967296",0x409,0,&ui)==DISP_E_OVERFLOW && ui==UINT32_MAX);
    CHECK(VarUI4FromStr((const WCHAR *)L"2.5",0x409,0,&ui)==S_OK && ui==2);
    CHECK(VarUI4FromStr((const WCHAR *)L"3.5",0x409,0,&ui)==S_OK && ui==4);
    CHECK(VarUI4FromStr((const WCHAR *)L"-1",0x409,0,&ui)==DISP_E_OVERFLOW);
    CHECK(VarDecFromStr((const WCHAR *)L"1",0x412,0,&out)==HRESULT_FROM_WIN32(ERROR_INVALID_PARAMETER));
    locale_fail=1; saved=out;
    CHECK(VarDecFromStr((const WCHAR *)L"1",0x409,0,&out)==HRESULT_FROM_WIN32(ERROR_ACCESS_DENIED) && !memcmp(&saved,&out,sizeof out));
    CHECK(VarBstrFromDec(&d,0x409,0,&b)==HRESULT_FROM_WIN32(ERROR_ACCESS_DENIED) && !b && !bstr_live);
    locale_fail=0;
    CHECK(VarBstrFromDec(&d,0x409,0,&b)==S_OK && !host_wcsncmp(b,(const WCHAR *)L"123.45",7) && bstr_live==1);
    CHECK(*(DWORD *)((BYTE *)b-4)==12); SysFreeString(b); CHECK(!bstr_live);
    alloc_fail=1; CHECK(VarBstrFromDec(&d,0x409,0,&b)==E_OUTOFMEMORY && !b); alloc_fail=0;
    format_fail=1; CHECK(VarBstrFromDec(&d,0x409,LOCALE_USE_NLS,&b)==HRESULT_FROM_WIN32(ERROR_ACCESS_DENIED) && !b && !bstr_live); format_fail=0;
    CHECK(VarBstrFromDec(&d,0x409,LOCALE_USE_NLS,&b)==S_OK && !host_wcsncmp(b,(const WCHAR *)L"provider:123.45",16) && format_calls==2);
    SysFreeString(b); CHECK(!bstr_live);
    { union { DECIMAL input; BSTR output; } alias; alias.input=d;
      CHECK(VarBstrFromDec(&alias.input,0x409,0,&alias.output)==S_OK && !host_wcsncmp(alias.output,(const WCHAR *)L"123.45",7)); SysFreeString(alias.output); }
}
static pthread_mutex_t worker_start_lock = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t worker_start_condition = PTHREAD_COND_INITIALIZER;
static unsigned worker_ready;
static void *worker(void *arg)
{
    ULONG64 k=(ULONG64)(uintptr_t)arg; unsigned i;
    pthread_mutex_lock(&worker_start_lock);
    if (++worker_ready == 2) pthread_cond_broadcast(&worker_start_condition);
    while (worker_ready != 2) pthread_cond_wait(&worker_start_condition, &worker_start_lock);
    pthread_mutex_unlock(&worker_start_lock);
    for(i=0;i<1000;i++) {
        DECIMAL a=dec(k+i,0,2,0),b=dec(2,0,0,0),out; BSTR s=NULL;
        DECIMAL scaled=dec(k+i+1000,0,2,0);
        if (VarDecAdd(&scaled,&b,&out)!=S_OK || !equal(out,dec(k+i+1200,0,2,0))) return (void *)3;
        if (VarDecAdd(&b,&scaled,&out)!=S_OK || !equal(out,dec(k+i+1200,0,2,0))) return (void *)4;
        if (VarDecSub(&scaled,&b,&out)!=S_OK || !equal(out,dec(k+i+800,0,2,0))) return (void *)5;
        if (VarDecSub(&b,&scaled,&out)!=S_OK || !equal(out,dec(k+i+800,0,2,0x80))) return (void *)6;
        if(VarDecMul(&a,&b,&out)!=S_OK || !equal(out,dec(2*(k+i),0,2,0)) || VarBstrFromDec(&a,0x409,0,&s)!=S_OK || !s) return (void *)1;
        SysFreeString(s); if(bstr_live) return (void *)2;
    }
    return NULL;
}
int main(void)
{
    pthread_t a,b; void *ra,*rb;
    integer_oracle(); arithmetic_oracle(); contract_edges(); string_edges();
    CHECK(!pthread_create(&a,NULL,worker,(void *)(uintptr_t)100));
    CHECK(!pthread_create(&b,NULL,worker,(void *)(uintptr_t)7000));
    CHECK(!pthread_join(a,&ra) && !pthread_join(b,&rb) && !ra && !rb);
    CHECK(!bstr_live);
    printf("PASS %u checks; independent integer/rational vectors, alias, NLS/BSTR errors and two real pthreads\n",checks);
    return 0;
}
