/* SPDX-License-Identifier: GPL-2.0-only
 *
 * ShizukuTrident Lite - the DOM: documents, nodes, attributes, live lists. Owner: core (dom.c, dom_attr.c,
 * dom_list.c, dom_text.c).
 *
 * The engine.h handle types ARE these structures: struct shzeng_doc / shzeng_node / shzeng_list are defined here (and
 * shzeng_event, shzeng_style, shzeng_sheet, shzeng_range, shzeng_view in the modules that own them), so the Windows glue
 * passes pointers through without casts. Core code uses the shorter shz_* typedef names.
 *
 * LIFETIME RULES (DESIGN.md section 4)
 * - node->refs counts every holder that is not the tree itself: engine.h handles given to the host, static lists,
 *   events, the parser's stack of open elements, Attr nodes (on their owner element), interaction state (focus/hover).
 * - A node is alive while refs > 0 OR it has a parent. When the last reference of a parentless node goes away the node
 *   is freed together with every descendant that has no reference of its own; a referenced descendant survives as the
 *   root of its own detached tree.
 * - The document: doc->refs counts engine.h document handles and internal holders that need the document open (fetch
 *   sinks, views). When it drops to 0 the document is CLOSED (parser destroyed, modules drop their internal node
 *   references); its memory (and the whole tree) is freed once it is closed AND no node of it is referenced
 *   (doc->pinned == 0: the number of nodes of this document with refs > 0). A node therefore keeps its document
 *   alive, so node_doc() never dangles.
 * - Node identity is the pointer: the DOM never copies a node behind the host's back.
 */
#ifndef SHZ_DOM_H
#define SHZ_DOM_H

#include "base.h"
#include "names.h"

typedef struct shzeng_doc shz_doc;
typedef struct shzeng_node shz_node;
typedef struct shzeng_list shz_list;
typedef struct shzeng_event shz_event;          /* events.h (L2) */
typedef struct shzeng_style shz_style;          /* css.h (L1) */
typedef struct shzeng_sheet shz_sheet;          /* css.h (L1) */
typedef struct shzeng_range shz_range;          /* range.c (core) */
typedef struct shz_fetch_sink shz_fetch_sink;   /* fetch.h (core) */
typedef struct shz_parser shz_parser;           /* html_parser.h (core) */

/* ---------------------------------------------------------------------------------------------------- node types */
enum {
    SHZ_ELEMENT_NODE = 1, SHZ_ATTRIBUTE_NODE = 2, SHZ_TEXT_NODE = 3, SHZ_CDATA_SECTION_NODE = 4,
    SHZ_PI_NODE = 7, SHZ_COMMENT_NODE = 8, SHZ_DOCUMENT_NODE = 9, SHZ_DOCTYPE_NODE = 10, SHZ_FRAGMENT_NODE = 11
};

/* namespaces */
enum { SHZ_NS_NONE = 0, SHZ_NS_HTML, SHZ_NS_SVG, SHZ_NS_MATHML, SHZ_NS_XML, SHZ_NS_XMLNS, SHZ_NS_XLINK, SHZ_NS_OTHER };

/* compareDocumentPosition bits */
#define SHZ_POS_DISCONNECTED  0x01
#define SHZ_POS_PRECEDING     0x02
#define SHZ_POS_FOLLOWING     0x04
#define SHZ_POS_CONTAINS      0x08
#define SHZ_POS_CONTAINED_BY  0x10
#define SHZ_POS_IMPL_SPECIFIC 0x20

/* node flags */
#define SHZ_NF_IN_DOC          0x0001   /* connected: a descendant of its document's Document node */
#define SHZ_NF_PARSER_INSERTED 0x0002   /* <script> created by the parser (not by parse_fragment) */
#define SHZ_NF_STARTED         0x0004   /* <script> "already started" (run_script was or will not be called) */
#define SHZ_NF_FREEING         0x0008   /* internal: being destroyed */
#define SHZ_NF_CREATED_BY_PARSER 0x0010 /* element created by the HTML parser (any kind) */

/* ---------------------------------------------------------------------------------------------------- nodes */
struct shzeng_node {
    uint32_t refs;
    uint16_t type;                      /* SHZ_*_NODE */
    uint16_t flags;                     /* SHZ_NF_* */
    shz_doc *doc;                       /* owner document (for the Document node: its own document) */
    shz_node *parent, *first_child, *last_child, *prev_sibling, *next_sibling;
    void *host_data;                    /* engine.h node_set_host_data (not reference counted) */
    struct shz_box *box;                /* L1 (layout.h): layout object(s) generated by this node */
    struct shz_listener *listeners;     /* L2 (events.h): event listeners registered on this node */
};

typedef struct shz_attr {
    shz_char *name;                     /* qualified name; lower-case on HTML elements of HTML documents */
    shz_char *value;                    /* never NULL */
    uint32_t value_len;
    uint16_t id;                        /* SHZ_ATTR_* (known HTML attribute name), 0 otherwise */
    uint16_t ns;                        /* SHZ_NS_* of the attribute (SHZ_NS_NONE normally) */
    shz_node *node;                     /* the Attr node handed out for this attribute (weak) */
} shz_attr;

typedef struct shz_element {
    shz_node node;
    uint16_t tag;                       /* SHZ_TAG_* (names.h) */
    uint8_t ns;                         /* SHZ_NS_* */
    uint8_t eflags;                     /* reserved */
    shz_char *qname;                    /* qualified name (lower-case for HTML elements in HTML documents) */
    const shz_char *local;              /* local name: qname after the prefix */
    uint32_t qname_len;
    shz_char *ns_uri;                   /* namespace URI when ns == SHZ_NS_OTHER, else NULL */
    shz_attr *attrs;
    uint32_t attr_count, attr_cap;
    /* module data, created lazily and freed by the owning module on SHZ_CHG_DESTROYED */
    struct shz_style_elem *style;       /* L1 (style.h): inline declaration block, computed style cache */
    struct shz_ctl *ctl;                /* L2 (forms.h): form control state (value, checkedness, selection) */
    struct shz_img *img;                /* L2 (image.h): <img>/<input type=image> image state */
} shz_element;

/* text, comment, CDATA section, processing instruction */
typedef struct shz_chardata {
    shz_node node;
    shz_char *data;                     /* NUL-terminated */
    uint32_t len, cap;
    shz_char *target;                   /* processing instructions only */
} shz_chardata;

typedef struct shz_doctype {
    shz_node node;
    shz_char *name, *public_id, *system_id;   /* public_id / system_id NULL when missing */
} shz_doctype;

/* Attr node (elem_attr_node). While owner != NULL it reflects owner's attribute `name` and holds a reference on the
 * owner; when that attribute is removed it keeps a copy of the last value. */
typedef struct shz_attrnode {
    shz_node node;
    shz_node *owner;
    shz_char *name;
    shz_char *value;                    /* only while detached */
} shz_attrnode;

static inline shz_element *shz_elem(shz_node *n)
{
    return n && n->type == SHZ_ELEMENT_NODE ? (shz_element *)n : NULL;
}
/* HTML element with the given SHZ_TAG_* id? */
static inline int shz_is_tag(const shz_node *n, int tag)
{
    return n && n->type == SHZ_ELEMENT_NODE && ((const shz_element *)n)->tag == tag
           && ((const shz_element *)n)->ns == SHZ_NS_HTML;
}
static inline int shz_tag_of(const shz_node *n)
{
    return n && n->type == SHZ_ELEMENT_NODE && ((const shz_element *)n)->ns == SHZ_NS_HTML ? ((const shz_element *)n)->tag : 0;
}
static inline int shz_is_chardata(const shz_node *n)
{
    return n && (n->type == SHZ_TEXT_NODE || n->type == SHZ_COMMENT_NODE || n->type == SHZ_CDATA_SECTION_NODE
                 || n->type == SHZ_PI_NODE);
}
static inline shz_chardata *shz_cdata(shz_node *n)
{
    return shz_is_chardata(n) ? (shz_chardata *)n : NULL;
}
static inline int shz_is_text(const shz_node *n)
{
    return n && (n->type == SHZ_TEXT_NODE || n->type == SHZ_CDATA_SECTION_NODE);
}
static inline int shz_in_doc(const shz_node *n) { return n && (n->flags & SHZ_NF_IN_DOC); }

/* ---------------------------------------------------------------------------------------------------- documents */
/* Host callbacks in core types (the glue adapts engine.h's shzeng_host to this; the host tests implement it). Every
 * member may be NULL. They mirror shzeng_host exactly (see engine.h for the semantics). */
typedef struct shz_doc_hooks {
    void    (*node_inserted)(void *ctx, shz_doc *doc, shz_node *node);
    void    (*node_removed)(void *ctx, shz_doc *doc, shz_node *node);
    void    (*parse_done)(void *ctx, shz_doc *doc);
    void    (*run_script)(void *ctx, shz_doc *doc, shz_node *script, int parser_inserted);
    shz_res (*event)(void *ctx, shz_node *current_target, shz_event *ev, void *cookie);   /* SHZ_FALSE: preventDefault */
    shz_res (*fetch)(void *ctx, shz_doc *doc, const shz_char *url, int kind, shz_fetch_sink *sink);
    void    (*load_done)(void *ctx, shz_doc *doc);
    void    (*title_changed)(void *ctx, shz_doc *doc);
    void    (*status_text)(void *ctx, const shz_char *text);
    shz_res (*navigate)(void *ctx, shz_doc *doc, const shz_char *url, const shz_char *target, const void *post,
                        size_t post_len, const shz_char *headers);
    void    (*context_menu)(void *ctx, shz_doc *doc, int32_t screen_x, int32_t screen_y, shz_node *node);
    void    (*invalidate)(void *ctx, shz_doc *doc, const shz_irect *rect);
} shz_doc_hooks;

/* document modes: the values of engine.h shzeng_mode */
enum { SHZ_MODE_QUIRKS = 0, SHZ_MODE_IE5, SHZ_MODE_IE7, SHZ_MODE_IE8, SHZ_MODE_IE9, SHZ_MODE_IE10, SHZ_MODE_IE11 };
/* rendering modes (HTML "quirks mode" / "limited-quirks mode" / "no-quirks mode") */
enum { SHZ_QUIRKS_NONE = 0, SHZ_QUIRKS_LIMITED = 1, SHZ_QUIRKS_FULL = 2 };
/* document.readyState */
enum { SHZ_READY_UNINITIALIZED = 0, SHZ_READY_LOADING, SHZ_READY_INTERACTIVE, SHZ_READY_COMPLETE };

struct shzeng_doc {
    uint32_t refs;                      /* document handles + internal holders that keep it open (fetch sinks, views) */
    uint32_t pinned;                    /* nodes of this document with refs > 0 */
    uint8_t closed;                     /* refs reached 0: parser and module state torn down */
    uint8_t freeing;
    uint8_t is_html;                    /* HTML document (else XML: case-sensitive names, no HTML parser rules) */
    uint8_t scripting;                  /* HTML "scripting flag" (<noscript> is raw text); always 1 here */
    shz_node *node;                     /* the Document node */
    shz_char *url;                      /* document URL ("about:blank" by default) */
    shz_char *content_type;             /* "text/html", "application/xml", ... */
    shz_char *charset;                  /* the encoding the parser used ("UTF-8", "windows-1252", "UTF-16LE"...) */
    uint64_t version;                   /* bumped by every tree or attribute mutation (validates live-list caches) */

    /* modes: doc_set_mode stores the Trident mode; until it is called the doctype decides (HTML5 rules) */
    int mode;                           /* SHZ_MODE_* */
    uint8_t mode_set;                   /* doc_set_mode was called */
    uint8_t doctype_quirks;             /* SHZ_QUIRKS_* from the doctype the parser saw */

    const shz_doc_hooks *hooks;
    void *hooks_ctx;
    void *platform;                     /* the Windows glue's per-document data (engine.h host + ctx) */
    void (*platform_free)(void *platform);  /* called when the document is freed */

    shz_parser *parser;                 /* active HTML parser, or NULL */
    int ready_state;                    /* SHZ_READY_*; written by the loader (loader.h, L2) and the parser */
    uint32_t fetch_pending;             /* sub-resource fetches in flight that delay "load" (fetch.c) */
    shz_range *selection;               /* the document selection (sel_get/sel_set), reference held */
    shz_range *live_ranges;             /* every range of this document (range.c keeps boundaries valid) */

    /* interaction state: written by L2 (events/view/forms), read by selectors (:hover/:focus/:active) and L1 paint.
     * References are held; L2 clears them when the node leaves the document (SHZ_CHG_REMOVED) and on close. */
    shz_node *focus;                    /* focused element (NULL = the document/body) */
    shz_node *hover;                    /* innermost element under the mouse */
    shz_node *active;                   /* element being activated (mouse button down) */

    /* viewport: written by the view (L2) / snapshot / view_paint (L1), read by layout */
    int32_t viewport_w, viewport_h;     /* initial containing block size in CSS px */
    int32_t scroll_x, scroll_y;         /* viewport scroll position */
    float zoom;                         /* 1.0 */

    /* module state, owned by the named module and released on SHZ_CHG_DOC_CLOSED */
    struct shz_css_doc *css;            /* L1: style sheets, cascade caches */
    struct shz_layout_doc *layout;      /* L1: box tree, display list */
    struct shz_events_doc *events;      /* L2: window listeners, pending events */
    struct shz_forms_doc *forms;        /* L2 */
    struct shz_images_doc *images;      /* L2: image cache */
    struct shz_load_doc *load;          /* L2: readyState / DOMContentLoaded / load bookkeeping */
    struct shz_view_list *views;        /* L2 (win): views presenting this document */
};

/* Create a document (refs = 1). mime NULL = "text/html"; an XML type makes an XML document. hooks may be NULL. */
shz_res   shz_doc_create(const shz_doc_hooks *hooks, void *hooks_ctx, const shz_char *url, const shz_char *mime,
                         shz_doc **out);
void      shz_doc_addref(shz_doc *doc);
void      shz_doc_release(shz_doc *doc);
shz_res   shz_doc_set_url(shz_doc *doc, const shz_char *url);
/* engine.h doc_set_mode: store the Trident document mode (SHZ_MODE_*); modules restyle (SHZ_CHG_MODE). */
shz_res   shz_doc_set_mode(shz_doc *doc, int mode);
/* Remove every child of the Document node (load_string, document.open). Notifies node_removed. */
void      shz_doc_clear(shz_doc *doc);
/* The rendering mode layout uses (SHZ_QUIRKS_*): from doc->mode when doc_set_mode was called (QUIRKS/IE5 -> FULL,
 * IE7 -> LIMITED, IE8+ -> NONE), else doc->doctype_quirks. */
int       shz_doc_quirks(const shz_doc *doc);
/* Tree accessors (no references added; NULL when absent). */
shz_node *shz_doc_element(shz_doc *doc);                       /* documentElement */
shz_node *shz_doc_head(shz_doc *doc);
shz_node *shz_doc_body(shz_doc *doc);                          /* <body> or <frameset> child of <html> */
shz_node *shz_doc_doctype(shz_doc *doc);
shz_node *shz_doc_get_element_by_id(shz_doc *doc, const shz_char *id);
/* Resolve a URL reference against the document base URL (the first <base href> of <head>, itself resolved against
 * the document URL; else the document URL). Allocated; NULL on OOM. */
shz_char *shz_doc_resolve_url(shz_doc *doc, const shz_char *rel);
/* The document title: text of the first <title> with whitespace stripped and collapsed (allocated, "" if none). */
shz_char *shz_doc_title(shz_doc *doc);

/* ---------------------------------------------------------------------------------------------------- creation */
/* All constructors return a new node with refs = 1 (NULL on OOM). */
/* HTML element in the HTML namespace; name is lower-cased when doc->is_html. */
shz_node *shz_create_element(shz_doc *doc, const shz_char *name, size_t n);
shz_node *shz_create_element_tag(shz_doc *doc, int tag);       /* known HTML tag by id */
/* Element in a namespace (createElementNS). ns_uri NULL/"" = no namespace. The qualified name is kept as given. */
shz_node *shz_create_element_ns(shz_doc *doc, const shz_char *ns_uri, const shz_char *qname, size_t n);
/* Element in one of the well-known namespaces (the parser uses it for <svg>/<math> content). */
shz_node *shz_create_element_in(shz_doc *doc, int ns, const shz_char *name, size_t n);
shz_node *shz_create_text(shz_doc *doc, const shz_char *s, size_t n);
shz_node *shz_create_comment(shz_doc *doc, const shz_char *s, size_t n);
shz_node *shz_create_cdata(shz_doc *doc, const shz_char *s, size_t n);
shz_node *shz_create_pi(shz_doc *doc, const shz_char *target, const shz_char *data, size_t n);
shz_node *shz_create_fragment(shz_doc *doc);
shz_node *shz_create_doctype(shz_doc *doc, const shz_char *name, const shz_char *public_id, const shz_char *system_id);
/* Well-known namespace URIs (ASCII) */
const char *shz_ns_uri_ascii(int ns);                          /* NULL for SHZ_NS_NONE / OTHER */
int       shz_ns_from_uri(const shz_char *uri);                /* SHZ_NS_NONE for NULL/"", SHZ_NS_OTHER if unknown */
shz_char *shz_elem_namespace(shz_node *elem);                  /* namespace URI (allocated) or NULL */
/* Is name[0..n) acceptable as an element/attribute name for createElement/setAttribute? */
int       shz_is_valid_name(const shz_char *name, size_t n);

/* ---------------------------------------------------------------------------------------------------- refcount */
void      shz_node_addref(shz_node *node);
void      shz_node_release(shz_node *node);

/* ---------------------------------------------------------------------------------------------------- tree */
/* DOM mutation with the DOM Standard's validity checks (SHZ_E_HIERARCHY, SHZ_E_NOT_FOUND ...). A fragment child
 * inserts its children. The node is removed from its old parent (and adopted into parent's document) first.
 * Notifications: modules (observe.h) and host->node_inserted per newly connected node, in tree order;
 * host->node_removed per disconnected node. ref NULL = append. */
shz_res   shz_node_insert_before(shz_node *parent, shz_node *child, shz_node *ref);
shz_res   shz_node_append(shz_node *parent, shz_node *child);
shz_res   shz_node_remove_child(shz_node *parent, shz_node *child);
shz_res   shz_node_replace_child(shz_node *parent, shz_node *child, shz_node *old);
void      shz_node_remove(shz_node *node);                     /* detach from its parent, if any */
shz_res   shz_node_clone(shz_node *node, int deep, shz_node **out);
int       shz_node_contains(const shz_node *node, const shz_node *other);   /* inclusive */
unsigned  shz_node_compare_position(shz_node *node, shz_node *other);
shz_node *shz_node_root(shz_node *node);
size_t    shz_node_index(const shz_node *node);                /* position among its siblings */
size_t    shz_node_child_count(const shz_node *node);
shz_node *shz_node_child_at(shz_node *node, size_t index);
/* pre-order traversal inside root (root itself excluded from the "next" steps) */
shz_node *shz_node_next(shz_node *node, const shz_node *root);                 /* next node in tree order */
shz_node *shz_node_next_skip(shz_node *node, const shz_node *root);            /* next, skipping node's subtree */
shz_node *shz_node_next_element(shz_node *node, const shz_node *root);
shz_node *shz_first_element_child(shz_node *node);
shz_node *shz_next_element_sibling(shz_node *node);
shz_node *shz_prev_element_sibling(shz_node *node);
/* nearest inclusive ancestor that is an HTML element with the given tag (NULL if none) */
shz_node *shz_node_ancestor_tag(shz_node *node, int tag);

/* ---------------------------------------------------------------------------------------------------- names */
/* nodeName: upper-case qualified name for HTML elements in HTML documents, "#text", "#document", ... (allocated) */
shz_char *shz_node_name(shz_node *node);
/* nodeValue: character data / attribute value (allocated), NULL for other nodes */
shz_char *shz_node_value(shz_node *node);
shz_res   shz_node_set_value(shz_node *node, const shz_char *value);

/* ---------------------------------------------------------------------------------------------------- text */
/* textContent (allocated; NULL for the document and doctypes). */
shz_char *shz_node_text_content(shz_node *node);
/* innerText: rendered text (display from style.h shz_style_display, line breaks between blocks, <br> -> "\n",
 * whitespace collapsed outside pre). Allocated. */
shz_char *shz_node_inner_text(shz_node *node);
/* textContent setter: replace the children by one text node (none for ""); character data: set the data. */
shz_res   shz_node_set_text_content(shz_node *node, const shz_char *text);
/* character data */
shz_res   shz_chardata_set(shz_node *node, const shz_char *s, size_t n);
shz_res   shz_chardata_append(shz_node *node, const shz_char *s, size_t n);
shz_res   shz_chardata_replace(shz_node *node, uint32_t offset, uint32_t count, const shz_char *s, size_t n);
/* splitText: the tail becomes a new text node after node (refs = 1 in *tail) */
shz_res   shz_text_split(shz_node *text, uint32_t offset, shz_node **tail);

/* ---------------------------------------------------------------------------------------------------- attributes */
/* Name matching: on HTML elements of HTML documents the name is compared ASCII case-insensitively (stored lower-case);
 * elsewhere exactly. */
shz_attr *shz_elem_find_attr(shz_node *elem, const shz_char *name, size_t n);
shz_attr *shz_elem_find_attr_id(shz_node *elem, int attr_id);
const shz_char *shz_elem_attr(shz_node *elem, int attr_id);                    /* value or NULL */
const shz_char *shz_elem_attr_str(shz_node *elem, const shz_char *name);       /* value or NULL */
int       shz_elem_has_attr(shz_node *elem, int attr_id);
/* setAttribute: SHZ_E_INVALID_CHAR for an invalid name. Notifies modules (SHZ_CHG_ATTR) and bumps doc->version. */
shz_res   shz_elem_set_attr(shz_node *elem, const shz_char *name, size_t n, const shz_char *value, size_t vn);
shz_res   shz_elem_set_attr_id(shz_node *elem, int attr_id, const shz_char *value);
/* removeAttribute: SHZ_OK when removed, SHZ_FALSE when there was none */
shz_res   shz_elem_remove_attr(shz_node *elem, const shz_char *name, size_t n);
/* The Attr node of an attribute (same node while the attribute exists); SHZ_FALSE + NULL when absent. */
shz_res   shz_elem_attr_node(shz_node *elem, const shz_char *name, size_t n, shz_node **out);
/* Parser/clone fast path: append an attribute without notifications (element not yet in any tree, no duplicate). */
shz_res   shz_elem_add_attr_raw(shz_node *elem, const shz_char *name, size_t n, const shz_char *value, size_t vn);
/* Attr node value / name */
const shz_char *shz_attrnode_value(shz_node *attr);
const shz_char *shz_attrnode_name(shz_node *attr);
/* class attribute contains cls (ASCII case-insensitive in quirks mode, as selectors require)? */
int       shz_elem_has_class(shz_node *elem, const shz_char *cls, size_t n);

/* ---------------------------------------------------------------------------------------------------- lists */
typedef enum {
    SHZ_LIST_STATIC = 0,                /* snapshot (query_selector all); holds references on its nodes */
    SHZ_LIST_CHILDREN,                  /* childNodes of root (live) */
    SHZ_LIST_BY_TAG,                    /* getElementsByTagName: "*" = all (live, root excluded) */
    SHZ_LIST_BY_TAG_NS,                 /* getElementsByTagNameNS(ns, local) */
    SHZ_LIST_BY_CLASS,                  /* getElementsByClassName (space-separated set) */
    SHZ_LIST_BY_NAME,                   /* getElementsByName (name attribute) */
    SHZ_LIST_COLLECTION                 /* document collections (engine.h shzeng_collection) */
} shz_list_kind;

/* engine.h shzeng_collection values */
enum { SHZ_COLL_ALL = 0, SHZ_COLL_FORMS, SHZ_COLL_IMAGES, SHZ_COLL_LINKS, SHZ_COLL_ANCHORS, SHZ_COLL_SCRIPTS,
       SHZ_COLL_APPLETS, SHZ_COLL_EMBEDS };

struct shzeng_list {
    uint32_t refs;
    uint8_t kind;                       /* shz_list_kind */
    uint8_t coll;                       /* SHZ_COLL_* for SHZ_LIST_COLLECTION */
    shz_node *root;                     /* reference held (NULL for static lists) */
    shz_char *arg, *arg2;               /* tag / class set / name / namespace URI */
    shz_vec items;                      /* static: the nodes (referenced); live: the cache (not referenced) */
    shz_doc *cache_doc;                 /* live cache validity: root->doc and its version when built */
    uint64_t cache_version;
    uint8_t cache_valid;
};

shz_list *shz_list_new_static(void);
shz_res   shz_list_static_push(shz_list *list, shz_node *node);  /* adds a reference */
shz_list *shz_list_children(shz_node *node);
/* by: 0 tag, 1 class, 2 name, 3 tag with namespace (engine.h shzeng_by) */
shz_list *shz_list_by(shz_node *root, int by, const shz_char *ns, const shz_char *value);
shz_list *shz_list_collection(shz_doc *doc, int which);
void      shz_list_addref(shz_list *list);
void      shz_list_release(shz_list *list);
uint32_t  shz_list_length(shz_list *list);
shz_node *shz_list_item(shz_list *list, uint32_t index);        /* no reference added; NULL out of range */
/* HTMLCollection namedItem: first element whose id is name, or an HTML element whose name attribute is name */
shz_node *shz_list_named_item(shz_list *list, const shz_char *name);

/* ---------------------------------------------------------------------------------------------------- internals */
/* Used by the parser: insert without the DOM validity checks (child must be parentless), with notifications. */
void      shz_dom_insert_raw(shz_node *parent, shz_node *child, shz_node *ref);
/* Title bookkeeping: called after text inside a <title> changed. */
void      shz_dom_title_maybe_changed(shz_doc *doc, shz_node *changed);

#endif /* SHZ_DOM_H */
