/* SPDX-License-Identifier: GPL-2.0-only
 * tridentrt: registry seeding for the Wine browser stack.
 *
 * The Shizuku registry is volatile (in-kernel, empty HKCR at every boot) and there is no setup step, regsvr32 or
 * advpack, so the keys the browser modules' DllRegisterServer would write are written here instead, before the first
 * activation, ProgID or type library lookup of a process (activation.c, type library wrappers in tlbhook.c), and on
 * demand through the export ShzTridentRegister. The browser DLLs themselves are never loaded for it (mshtml's
 * DllRegisterServer would need advpack, and loading every DLL to read its registration resources costs more than the
 * table).
 *
 * What is written: register_table.h, generated by gen_register.py from the pinned Wine tree. It holds, per key and
 * value, the registration Wine produces for (sources in the table's comments, one per group of rows):
 *   CLSIDs + InprocServer32 (C:\SHZ\SYS64\<dll>) + ThreadingModel + ProgID/VersionIndependentProgID of every
 *     coclass the ported DLLs serve: mshtml (widl -r mshtml_classes.idl: HTMLDocument, AboutProtocol, ResProtocol,
 *     JSProtocol, MailtoProtocol, ...), urlmon (urlmon_urlmon.idl: the file/http/https/ftp/... protocol handlers,
 *     StdURLMoniker, the security and zone managers, ...), ieframe (ieframe_v1.idl + exdisp.idl via the SHDocVw
 *     type library: WebBrowser, WebBrowser_V1, InternetExplorer, ShellUIHelper, ...), jscript (jscript_classes.idl:
 *     JScript = "JScript"/"JavaScript" ProgIDs from jscript.rgs, JScriptEncode, JScriptAuthor), msxml3 (msxml3_v1.idl:
 *     DOMDocument(2.6/3.0), FreeThreadedDOMDocument, XMLHTTP(3.0), ServerXMLHTTP, SAXXMLReader, ...;
 *     xmlparser.idl), oleacc (oleacc_classes.idl);
 *   ProgID keys (Shell.Explorer(.1/.2), JScript, JavaScript, Msxml2.XMLHTTP(.3.0), Microsoft.XMLHTTP,
 *     Msxml2.DOMDocument(.3.0), Microsoft.XMLDOM, ...) with CLSID and CurVer;
 *   TypeLib registrations (0\win64 paths): stdole {00020430-0000-0000-C000-000000000046} 2.0 -> stdole2.tlb,
 *     MSHTML {3050F1C5-98B5-11CF-BB82-00AA00BDCE0B} 4.0 -> mshtml.tlb, SHDocVw {EAB22AC0-30C1-11CF-A7EB-0000C05BAE0B}
 *     1.1 -> ieframe.dll, MSXML2 {F5078F18-C551-11D3-89B9-0000F81FE221} 3.0 -> msxml3.dll, JSGlobal -> jscript.dll,
 *     Accessibility -> oleacc.dll;
 *   mshtml.inf RegisterDll: HKCR\MIME\Database\Content Type\text/html (CLSID = HTMLDocument) and the other content
 *     types, .htm/.html/.txt/... "Content Type", htmlfile, PROTOCOLS\Handler\{about,res,javascript,vbscript,mailto,
 *     sysimage}, HKLM\Software\Microsoft\Internet Explorer\{AboutURLs,Version Vector,...};
 *   urlmon.rgs: PROTOCOLS\Handler\{file,local,http,https,ftp,gopher,mk,cdl}, PROTOCOLS\Filter\{deflate,gzip,...},
 *     HKCU Internet Settings "User Agent"; urlmon.inf RegisterDll: HKCU/HKLM ...\Internet Settings\ZoneMap
 *     (ProtocolDefaults http/https/ftp/file = 3, @ivt = 1, Domains, Ranges) and the Zones\0..4 policies;
 *   ieframe.rgs: HKLM ...\CurrentVersion\URL (DefaultPrefix, Prefixes), InternetShortcut, .url, URL Protocol markers;
 *   jscript.rgs: OLEScript/Implemented Categories of the script engines, JScript/JavaScript ProgIDs, JSFile;
 *   Shizuku: HKLM\Software\Wine\MSHTML\2.47.4 GeckoPath = C:\SHZ\SYS64\gecko (dlls/mshtml/nsembed.c
 *     find_wine_gecko_reg reads it; the fake-Gecko xul.dll lives there).
 * Not written: HKCR\Interface (marshaling registrations; no cross-apartment marshaling exists) and HKCR\Component
 * Categories names.
 *
 * "When missing": a value that exists already is never overwritten (a user or a test may have changed it); keys are
 * created as needed. HKLM\Software\Shizuku\Trident "RegistryStamp" (REG_DWORD) records the table version seeded in this
 * boot, so later processes skip the walk with one registry read.
 */
#include "comrt.h"

struct trt_reg_row
{
    HKEY root;
    const WCHAR *key;
    const WCHAR *name;          /* NULL: the key's default value */
    DWORD type;                 /* REG_NONE: create the key only */
    const WCHAR *str;           /* REG_SZ / REG_EXPAND_SZ */
    DWORD num;                  /* REG_DWORD value, REG_BINARY size */
    const char *bin;            /* REG_BINARY */
};

#include "register_table.h"

static const WCHAR stamp_key[] = L"Software\\Shizuku\\Trident";
static const WCHAR stamp_value[] = L"RegistryStamp";

static LONG seed_rows(void)
{
    const struct trt_reg_row *row, *end = trt_reg_rows + ARRAY_SIZE(trt_reg_rows);
    const struct trt_reg_row *open_row = NULL;
    LONG first_error = ERROR_SUCCESS, res;
    HKEY key = 0;
    DWORD size;

    for (row = trt_reg_rows; row < end; row++)
    {
        if (!open_row || open_row->root != row->root || lstrcmpiW(open_row->key, row->key))
        {
            if (key) RegCloseKey(key);
            key = 0;
            open_row = row;
            res = RegCreateKeyExW(row->root, row->key, 0, NULL, 0, KEY_ALL_ACCESS, NULL, &key, NULL);
            if (res)
            {
                key = 0;
                if (!first_error) first_error = res;
                continue;
            }
        }
        if (!key || row->type == REG_NONE) continue;
        if (!RegQueryValueExW(key, row->name, NULL, NULL, NULL, &size)) continue;       /* present: keep it */
        switch (row->type)
        {
        case REG_SZ:
        case REG_EXPAND_SZ:
            res = RegSetValueExW(key, row->name, 0, row->type, (const BYTE *)row->str,
                                 (lstrlenW(row->str) + 1) * sizeof(WCHAR));
            break;
        case REG_DWORD:
            res = RegSetValueExW(key, row->name, 0, REG_DWORD, (const BYTE *)&row->num, sizeof(DWORD));
            break;
        default:
            res = RegSetValueExW(key, row->name, 0, row->type, (const BYTE *)row->bin, row->num);
            break;
        }
        if (res && !first_error) first_error = res;
    }
    if (key) RegCloseKey(key);
    return first_error;
}

static void write_stamp(void)
{
    DWORD stamp = TRT_REG_STAMP;
    HKEY key;
    if (RegCreateKeyExW(HKEY_LOCAL_MACHINE, stamp_key, 0, NULL, 0, KEY_SET_VALUE, NULL, &key, NULL)) return;
    RegSetValueExW(key, stamp_value, 0, REG_DWORD, (const BYTE *)&stamp, sizeof(stamp));
    RegCloseKey(key);
}

static BOOL stamp_current(void)
{
    DWORD stamp = 0, size = sizeof(stamp), type;
    HKEY key;
    LONG res;
    if (RegOpenKeyExW(HKEY_LOCAL_MACHINE, stamp_key, 0, KEY_QUERY_VALUE, &key)) return FALSE;
    res = RegQueryValueExW(key, stamp_value, NULL, &type, (BYTE *)&stamp, &size);
    RegCloseKey(key);
    return !res && type == REG_DWORD && stamp == TRT_REG_STAMP;
}

HRESULT WINAPI ShzTridentRegister(void)
{
    LONG res = seed_rows();
    if (!res) write_stamp();
    return HRESULT_FROM_WIN32(res);
}

void trt_register_once(void)
{
    static LONG state;                                      /* 0 not yet, 1 running, 2 done */
    if (state == 2) return;
    if (InterlockedCompareExchange(&state, 1, 0) == 0)
    {
        if (!stamp_current()) ShzTridentRegister();
        InterlockedExchange(&state, 2);
        return;
    }
    while (state != 2) Sleep(1);                            /* another thread is seeding */
}
