# SPDX-License-Identifier: GPL-2.0-only
# tridentrt.dll exports (wineport/build.py reads this Wine-format spec: "@ stdcall Name(args) [implementation]").
# COM/OLE/shlwapi/kernel32 functions the Wine browser modules import and the Shizuku runtime lacks; the browser
# modules link tridentrt before ole32/oleaut32/shlwapi (and kernel32), so these names bind here. An entry is exported
# only if its body does real work (winespec.py drops stubs). Implementations:
#   Wine, unmodified, from the pinned tree: dlls/oleaut32/{typelib.c (+ patch 0200), thunks.c, hash.c, dispatch.c,
#     variant.c, vartype.c}, dlls/ole32/{bindctx.c, oleobj.c}, dlls/combase/hglobalstream.c,
#     dlls/kernelbase/path.c (the URL functions; the rest of path.c is not exported)
#   Shizuku-original, shizukudos/win64/trident/comrt/: activation.c, errorinfo.c, rot.c, ole.c, tlbhook.c,
#     shlwapi.c, kernel32.c, register.c
# BSTR/SAFEARRAY allocation, VariantInit/Clear/Copy and the other functions the Shizuku oleaut32 exports stay there
# (not re-exported), except VariantChangeType(Ex) and LoadRegTypeLib, which replace the partial Shizuku versions.

# ---------------------------------------------------------------- ole32 (activation.c, errorinfo.c, rot.c, ole.c)
@ stdcall CoGetClassObject(ptr long ptr ptr ptr)
@ stdcall CoCreateInstance(ptr ptr long ptr ptr)
@ stdcall CoCreateInstanceEx(ptr ptr long ptr long ptr)
@ stdcall CoRegisterClassObject(ptr ptr long long ptr)
@ stdcall CoRevokeClassObject(long)
@ stdcall CoResumeClassObjects()
@ stdcall CoSuspendClassObjects()
@ stdcall CLSIDFromProgID(wstr ptr)
@ stdcall CLSIDFromProgIDEx(wstr ptr)
@ stdcall ProgIDFromCLSID(ptr ptr)
@ stdcall OleRegGetUserType(ptr long ptr)
@ stdcall GetRunningObjectTable(long ptr)
@ stdcall GetErrorInfo(long ptr)
@ stdcall SetErrorInfo(long ptr)
@ stdcall CreateErrorInfo(ptr)
@ stdcall ReleaseStgMedium(ptr)
# Wine dlls/ole32/bindctx.c, dlls/ole32/oleobj.c, dlls/combase/hglobalstream.c
@ stdcall CreateBindCtx(long ptr)
@ stdcall CreateOleAdviseHolder(ptr)
@ stdcall CreateDataAdviseHolder(ptr)
@ stdcall CreateStreamOnHGlobal(ptr long ptr)
@ stdcall GetHGlobalFromStream(ptr ptr)

# ---------------------------------------------------------------- oleaut32
# type library loaders: registry seeding first (tlbhook.c), then Wine's typelib.c
@ stdcall LoadTypeLib(wstr ptr) trt_LoadTypeLib
@ stdcall LoadTypeLibEx(wstr long ptr) trt_LoadTypeLibEx
@ stdcall LoadRegTypeLib(ptr long long long ptr) trt_LoadRegTypeLib
@ stdcall QueryPathOfRegTypeLib(ptr long long long ptr) trt_QueryPathOfRegTypeLib
# BSTR <-> VT_UI1 vectors (ole.c, over the Shizuku SysAllocStringByteLen / SafeArrayCreate)
@ stdcall BstrFromVector(ptr ptr)
@ stdcall VectorFromBstr(ptr ptr)
# Wine typelib.c, dispatch.c, hash.c, variant.c, vartype.c
@ stdcall VariantChangeType(ptr ptr long long)
@ stdcall VariantTimeToDosDateTime(double ptr ptr)
@ stdcall DosDateTimeToVariantTime(long long ptr)
@ stdcall DispGetParam(ptr long long ptr ptr)
@ stdcall DispGetIDsOfNames(ptr ptr long ptr)
@ stdcall DispInvoke(ptr ptr long long ptr ptr ptr ptr)
@ stdcall CreateDispTypeInfo(ptr long ptr)
@ stdcall CreateStdDispatch(ptr ptr ptr ptr)
@ stdcall VarParseNumFromStr(wstr long long ptr ptr)
@ stdcall VarNumFromParseNum(ptr ptr long ptr)
@ stdcall VarI2FromUI1(long ptr)
@ stdcall VarI2FromI4(long ptr)
@ stdcall VarI2FromR4(float ptr)
@ stdcall VarI2FromR8(double ptr)
@ stdcall VarI2FromCy(int64 ptr)
@ stdcall VarI2FromDate(double ptr)
@ stdcall VarI2FromStr(wstr long long ptr)
@ stdcall VarI2FromDisp(ptr long ptr)
@ stdcall VarI2FromBool(long ptr)
@ stdcall VarI4FromUI1(long ptr)
@ stdcall VarI4FromI2(long ptr)
@ stdcall VarI4FromR4(float ptr)
@ stdcall VarI4FromR8(double ptr)
@ stdcall VarI4FromCy(int64 ptr)
@ stdcall VarI4FromDate(double ptr)
@ stdcall VarI4FromStr(wstr long long ptr)
@ stdcall VarI4FromDisp(ptr long ptr)
@ stdcall VarI4FromBool(long ptr)
@ stdcall VarR4FromUI1(long ptr)
@ stdcall VarR4FromI2(long ptr)
@ stdcall VarR4FromI4(long ptr)
@ stdcall VarR4FromR8(double ptr)
@ stdcall VarR4FromCy(int64 ptr)
@ stdcall VarR4FromDate(double ptr)
@ stdcall VarR4FromStr(wstr long long ptr)
@ stdcall VarR4FromDisp(ptr long ptr)
@ stdcall VarR4FromBool(long ptr)
@ stdcall VarR8FromUI1(long ptr)
@ stdcall VarR8FromI2(long ptr)
@ stdcall VarR8FromI4(long ptr)
@ stdcall VarR8FromR4(float ptr)
@ stdcall VarR8FromCy(int64 ptr)
@ stdcall VarR8FromDate(double ptr)
@ stdcall VarR8FromStr(wstr long long ptr)
@ stdcall VarR8FromDisp(ptr long ptr)
@ stdcall VarR8FromBool(long ptr)
@ stdcall VarDateFromUI1(long ptr)
@ stdcall VarDateFromI2(long ptr)
@ stdcall VarDateFromI4(long ptr)
@ stdcall VarDateFromR4(float ptr)
@ stdcall VarDateFromR8(double ptr)
@ stdcall VarDateFromCy(int64 ptr)
@ stdcall VarDateFromStr(wstr long long ptr)
@ stdcall VarDateFromDisp(ptr long ptr)
@ stdcall VarDateFromBool(long ptr)
@ stdcall VarCyFromUI1(long ptr)
@ stdcall VarCyFromI2(long ptr)
@ stdcall VarCyFromI4(long ptr)
@ stdcall VarCyFromR4(float ptr)
@ stdcall VarCyFromR8(double ptr)
@ stdcall VarCyFromDate(double ptr)
@ stdcall VarCyFromStr(wstr long long ptr)
@ stdcall VarCyFromDisp(ptr long ptr)
@ stdcall VarCyFromBool(long ptr)
@ stdcall VarBstrFromUI1(long long long ptr)
@ stdcall VarBstrFromI2(long long long ptr)
@ stdcall VarBstrFromI4(long long long ptr)
@ stdcall VarBstrFromR4(float long long ptr)
@ stdcall VarBstrFromR8(double long long ptr)
@ stdcall VarBstrFromCy(int64 long long ptr)
@ stdcall VarBstrFromDate(double long long ptr)
@ stdcall VarBstrFromDisp(ptr long long ptr)
@ stdcall VarBstrFromBool(long long long ptr)
@ stdcall VarBoolFromUI1(long ptr)
@ stdcall VarBoolFromI2(long ptr)
@ stdcall VarBoolFromI4(long ptr)
@ stdcall VarBoolFromR4(float ptr)
@ stdcall VarBoolFromR8(double ptr)
@ stdcall VarBoolFromDate(double ptr)
@ stdcall VarBoolFromCy(int64 ptr)
@ stdcall VarBoolFromStr(wstr long long ptr)
@ stdcall VarBoolFromDisp(ptr long ptr)
@ stdcall VarUI1FromI2(long ptr)
@ stdcall VarUI1FromI4(long ptr)
@ stdcall VarUI1FromR4(float ptr)
@ stdcall VarUI1FromR8(double ptr)
@ stdcall VarUI1FromCy(int64 ptr)
@ stdcall VarUI1FromDate(double ptr)
@ stdcall VarUI1FromStr(wstr long long ptr)
@ stdcall VarUI1FromDisp(ptr long ptr)
@ stdcall VarUI1FromBool(long ptr)
@ stdcall VarAdd(ptr ptr ptr)
@ stdcall VarAnd(ptr ptr ptr)
@ stdcall VarDiv(ptr ptr ptr)
@ stdcall DispCallFunc(ptr long long long long ptr ptr ptr)
@ stdcall VariantChangeTypeEx(ptr ptr long long long)
@ stdcall VarEqv(ptr ptr ptr)
@ stdcall VarIdiv(ptr ptr ptr)
@ stdcall VarImp(ptr ptr ptr)
@ stdcall VarMod(ptr ptr ptr)
@ stdcall VarMul(ptr ptr ptr)
@ stdcall VarOr(ptr ptr ptr)
@ stdcall VarPow(ptr ptr ptr)
@ stdcall VarSub(ptr ptr ptr)
@ stdcall RegisterTypeLib(ptr wstr wstr)
@ stdcall LHashValOfNameSys(long long wstr)
@ stdcall LHashValOfNameSysA(long long str)
@ stdcall VarXor(ptr ptr ptr)
@ stdcall VarAbs(ptr ptr)
@ stdcall VarFix(ptr ptr)
@ stdcall ClearCustData(ptr)
@ stdcall VarInt(ptr ptr)
@ stdcall VarNeg(ptr ptr)
@ stdcall VarNot(ptr ptr)
@ stdcall VarRound(ptr long ptr)
@ stdcall VarCmp(ptr ptr long long)
@ stdcall VarDecAdd(ptr ptr ptr)
@ stdcall VarDecDiv(ptr ptr ptr)
@ stdcall VarDecMul(ptr ptr ptr)
@ stdcall CreateTypeLib2(long wstr ptr)
@ stdcall VarDecSub(ptr ptr ptr)
@ stdcall VarDecAbs(ptr ptr)
@ stdcall SystemTimeToVariantTime(ptr ptr)
@ stdcall VariantTimeToSystemTime(double ptr)
@ stdcall UnRegisterTypeLib(ptr long long long long)
@ stdcall VarDecFix(ptr ptr)
@ stdcall VarDecInt(ptr ptr)
@ stdcall VarDecNeg(ptr ptr)
@ stdcall VarDecFromUI1(long ptr)
@ stdcall VarDecFromI2(long ptr)
@ stdcall VarDecFromI4(long ptr)
@ stdcall VarDecFromR4(float ptr)
@ stdcall VarDecFromR8(double ptr)
@ stdcall VarDecFromDate(double ptr)
@ stdcall VarDecFromCy(int64 ptr)
@ stdcall VarDecFromStr(wstr long long ptr)
@ stdcall VarDecFromDisp(ptr long ptr)
@ stdcall VarDecFromBool(long ptr)
@ stdcall VarDecRound(ptr long ptr)
@ stdcall VarDecCmp(ptr ptr)
@ stdcall VarI2FromI1(long ptr)
@ stdcall VarI2FromUI2(long ptr)
@ stdcall VarI2FromUI4(long ptr)
@ stdcall VarI2FromDec(ptr ptr)
@ stdcall VarI4FromI1(long ptr)
@ stdcall VarI4FromUI2(long ptr)
@ stdcall VarI4FromUI4(long ptr)
@ stdcall VarI4FromDec(ptr ptr)
@ stdcall VarR4FromI1(long ptr)
@ stdcall VarR4FromUI2(long ptr)
@ stdcall VarR4FromUI4(long ptr)
@ stdcall VarR4FromDec(ptr ptr)
@ stdcall VarR8FromI1(long ptr)
@ stdcall VarR8FromUI2(long ptr)
@ stdcall VarR8FromUI4(long ptr)
@ stdcall VarR8FromDec(ptr ptr)
@ stdcall VarDateFromI1(long ptr)
@ stdcall VarDateFromUI2(long ptr)
@ stdcall VarDateFromUI4(long ptr)
@ stdcall VarDateFromDec(ptr ptr)
@ stdcall VarCyFromI1(long ptr)
@ stdcall VarCyFromUI2(long ptr)
@ stdcall VarCyFromUI4(long ptr)
@ stdcall VarCyFromDec(ptr ptr)
@ stdcall VarBstrFromI1(long long long ptr)
@ stdcall VarBstrFromUI2(long long long ptr)
@ stdcall VarBstrFromUI4(long long long ptr)
@ stdcall VarBstrFromDec(ptr long long ptr)
@ stdcall VarBoolFromI1(long ptr)
@ stdcall VarBoolFromUI2(long ptr)
@ stdcall VarBoolFromUI4(long ptr)
@ stdcall VarBoolFromDec(ptr ptr)
@ stdcall VarUI1FromI1(long ptr)
@ stdcall VarUI1FromUI2(long ptr)
@ stdcall VarUI1FromUI4(long ptr)
@ stdcall VarUI1FromDec(ptr ptr)
@ stdcall VarDecFromI1(long ptr)
@ stdcall VarDecFromUI2(long ptr)
@ stdcall VarDecFromUI4(long ptr)
@ stdcall VarI1FromUI1(long ptr)
@ stdcall VarI1FromI2(long ptr)
@ stdcall VarI1FromI4(long ptr)
@ stdcall VarI1FromR4(float ptr)
@ stdcall VarI1FromR8(double ptr)
@ stdcall VarI1FromDate(double ptr)
@ stdcall VarI1FromCy(int64 ptr)
@ stdcall VarI1FromStr(wstr long long ptr)
@ stdcall VarI1FromDisp(ptr long ptr)
@ stdcall VarI1FromBool(long ptr)
@ stdcall VarI1FromUI2(long ptr)
@ stdcall VarI1FromUI4(long ptr)
@ stdcall VarI1FromDec(ptr ptr)
@ stdcall VarUI2FromUI1(long ptr)
@ stdcall VarUI2FromI2(long ptr)
@ stdcall VarUI2FromI4(long ptr)
@ stdcall VarUI2FromR4(float ptr)
@ stdcall VarUI2FromR8(double ptr)
@ stdcall VarUI2FromDate(double ptr)
@ stdcall VarUI2FromCy(int64 ptr)
@ stdcall VarUI2FromStr(wstr long long ptr)
@ stdcall VarUI2FromDisp(ptr long ptr)
@ stdcall VarUI2FromBool(long ptr)
@ stdcall VarUI2FromI1(long ptr)
@ stdcall VarUI2FromUI4(long ptr)
@ stdcall VarUI2FromDec(ptr ptr)
@ stdcall VarUI4FromUI1(long ptr)
@ stdcall VarUI4FromI2(long ptr)
@ stdcall VarUI4FromI4(long ptr)
@ stdcall VarUI4FromR4(float ptr)
@ stdcall VarUI4FromR8(double ptr)
@ stdcall VarUI4FromDate(double ptr)
@ stdcall VarUI4FromCy(int64 ptr)
@ stdcall VarUI4FromStr(wstr long long ptr)
@ stdcall VarUI4FromDisp(ptr long ptr)
@ stdcall VarUI4FromBool(long ptr)
@ stdcall VarUI4FromI1(long ptr)
@ stdcall VarUI4FromUI2(long ptr)
@ stdcall VarUI4FromDec(ptr ptr)
@ stdcall VarDecCmpR8(ptr double)
@ stdcall VarCyAdd(int64 int64 ptr)
@ stdcall VarCyMul(int64 int64 ptr)
@ stdcall VarCyMulI4(int64 long ptr)
@ stdcall VarCySub(int64 int64 ptr)
@ stdcall VarCyAbs(int64 ptr)
@ stdcall VarCyFix(int64 ptr)
@ stdcall VarCyInt(int64 ptr)
@ stdcall VarCyNeg(int64 ptr)
@ stdcall VarCyRound(int64 long ptr)
@ stdcall VarCyCmp(int64 int64)
@ stdcall VarCyCmpR8(int64 double)
@ stdcall VarR8Pow(double double ptr)
@ stdcall VarR4CmpR8(float double)
@ stdcall VarR8Round(double long ptr)
@ stdcall VarCat(ptr ptr ptr)
@ stdcall VarDateFromUdateEx(ptr long long ptr)
@ stdcall VarCyMulI8(int64 int64 ptr)
@ stdcall VarDateFromUdate(ptr long ptr)
@ stdcall VarUdateFromDate(double long ptr)
@ stdcall VarI8FromUI1(long long)
@ stdcall VarI8FromI2(long long)
@ stdcall VarI8FromR4(float long)
@ stdcall VarI8FromR8(double long)
@ stdcall VarI8FromCy(int64 ptr)
@ stdcall VarI8FromDate(double long)
@ stdcall VarI8FromStr(wstr long long ptr)
@ stdcall VarI8FromDisp(ptr long ptr)
@ stdcall VarI8FromBool(long long)
@ stdcall VarI8FromI1(long long)
@ stdcall VarI8FromUI2(long long)
@ stdcall VarI8FromUI4(long long)
@ stdcall VarI8FromDec(ptr ptr)
@ stdcall VarI2FromI8(int64 ptr)
@ stdcall VarI2FromUI8(int64 ptr)
@ stdcall VarI4FromI8(int64 ptr)
@ stdcall VarI4FromUI8(int64 ptr)
@ stdcall VarR4FromI8(int64 ptr)
@ stdcall VarR4FromUI8(int64 ptr)
@ stdcall VarR8FromI8(int64 ptr)
@ stdcall VarR8FromUI8(int64 ptr)
@ stdcall VarDateFromI8(int64 ptr)
@ stdcall VarDateFromUI8(int64 ptr)
@ stdcall VarCyFromI8(int64 ptr)
@ stdcall VarCyFromUI8(int64 ptr)
@ stdcall VarBstrFromI8(int64 long long ptr)
@ stdcall VarBstrFromUI8(int64 long long ptr)
@ stdcall VarBoolFromI8(int64 ptr)
@ stdcall VarBoolFromUI8(int64 ptr)
@ stdcall VarUI1FromI8(int64 ptr)
@ stdcall VarUI1FromUI8(int64 ptr)
@ stdcall VarDecFromI8(int64 ptr)
@ stdcall VarDecFromUI8(int64 ptr)
@ stdcall VarI1FromI8(int64 ptr)
@ stdcall VarI1FromUI8(int64 ptr)
@ stdcall VarUI2FromI8(int64 ptr)
@ stdcall VarUI2FromUI8(int64 ptr)
@ stdcall VarUI4FromI8(int64 ptr)
@ stdcall VarUI4FromUI8(int64 ptr)
@ stdcall VarI8FromUI8(int64 ptr)
@ stdcall VarUI8FromI8(int64 ptr)
@ stdcall VarUI8FromUI1(long ptr)
@ stdcall VarUI8FromI2(long ptr)
@ stdcall VarUI8FromR4(float ptr)
@ stdcall VarUI8FromR8(double ptr)
@ stdcall VarUI8FromCy(int64 ptr)
@ stdcall VarUI8FromDate(double ptr)
@ stdcall VarUI8FromStr(wstr long long ptr)
@ stdcall VarUI8FromDisp(ptr long ptr)
@ stdcall VarUI8FromBool(long ptr)
@ stdcall VarUI8FromI1(long ptr)
@ stdcall VarUI8FromUI2(long ptr)
@ stdcall VarUI8FromUI4(long ptr)
@ stdcall VarUI8FromDec(long ptr)
@ stdcall RegisterTypeLibForUser(ptr wstr wstr)
@ stdcall UnRegisterTypeLibForUser(ptr long long long long)

# ---------------------------------------------------------------- shlwapi
# Wine dlls/kernelbase/path.c: the URL functions and PathSearchAndQualify
@ stdcall ParseURLA(str ptr)
@ stdcall ParseURLW(wstr ptr)
@ stdcall UrlUnescapeA(str ptr ptr long)
@ stdcall UrlUnescapeW(wstr ptr ptr long)
@ stdcall PathCreateFromUrlA(str ptr ptr long)
@ stdcall PathCreateFromUrlW(wstr ptr ptr long)
@ stdcall PathCreateFromUrlAlloc(wstr ptr long)
@ stdcall PathIsURLA(str)
@ stdcall PathIsURLW(wstr)
@ stdcall UrlEscapeA(str ptr ptr long)
@ stdcall UrlEscapeW(wstr ptr ptr long)
@ stdcall UrlCanonicalizeA(str ptr ptr long)
@ stdcall UrlCanonicalizeW(wstr ptr ptr long)
@ stdcall UrlApplySchemeA(str ptr ptr long)
@ stdcall UrlApplySchemeW(wstr ptr ptr long)
@ stdcall UrlCompareA(str str long)
@ stdcall UrlCompareW(wstr wstr long)
@ stdcall UrlFixupW(wstr wstr long)
@ stdcall UrlGetLocationA(str)
@ stdcall UrlGetLocationW(wstr)
@ stdcall UrlGetPartA(str ptr ptr long long)
@ stdcall UrlGetPartW(wstr ptr ptr long long)
@ stdcall UrlIsA(str long)
@ stdcall UrlIsW(wstr long)
@ stdcall UrlIsOpaqueA(str)
@ stdcall UrlIsOpaqueW(wstr)
@ stdcall UrlIsNoHistoryA(str)
@ stdcall UrlIsNoHistoryW(wstr)
@ stdcall UrlCreateFromPathA(str ptr ptr long)
@ stdcall UrlCreateFromPathW(wstr ptr ptr long)
@ stdcall UrlCombineA(str str ptr ptr long)
@ stdcall UrlCombineW(wstr wstr ptr ptr long)
@ stdcall HashData(ptr long ptr long)
@ stdcall UrlHashA(str ptr long)
@ stdcall UrlHashW(wstr ptr long)
@ stdcall PathSearchAndQualifyA(str ptr long)
@ stdcall PathSearchAndQualifyW(wstr ptr long)
# shlwapi.c
@ stdcall SHRegOpenUSKeyW(wstr long long ptr long)
@ stdcall SHRegCloseUSKey(ptr)
@ stdcall SHRegQueryUSValueW(long wstr ptr ptr ptr long ptr long)
@ stdcall SHRegGetUSValueW(wstr wstr ptr ptr ptr long ptr long)
@ stdcall SHRegEnumUSValueW(long long ptr ptr ptr ptr ptr long)
@ stdcall IStream_Read(ptr ptr long)
@ stdcall IStream_Write(ptr ptr long)
@ stdcall SHSetParentHwnd(long ptr)
@ stdcall StrStrIA(str str)
@ stdcall GetMIMETypeSubKeyW(wstr ptr long)
@ stdcall SHStrDupW(wstr ptr)

# ---------------------------------------------------------------- kernel32 (kernel32.c)
@ stdcall MulDiv(long long long)
@ stdcall IdnToAscii(long wstr long ptr long)
@ stdcall IdnToUnicode(long wstr long ptr long)
@ stdcall DosDateTimeToFileTime(long long ptr)
@ stdcall FileTimeToDosDateTime(ptr ptr ptr)
@ stdcall GetComputerNameExA(long ptr ptr)

# ---------------------------------------------------------------- Shizuku (register.c)
@ stdcall ShzTridentRegister()
