#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate kernel32/unidata.h: the compact Unicode property tables behind the Shizuku NLS layer.

Source of truth is the Python `unicodedata` module of the machine that runs this script (the generated header records its
Unicode version). Nothing here is Windows' own NLS data: the tables give
  * general category, bidi class, decimal digit value, White_Space and a few script/width flags per code point (run-length
    encoded, binary searched),
  * simple (1:1) upper/lower case mappings, as UnicodeData.txt defines them,
  * canonical decompositions (BMP, NFD, at most 3 code points) and the matching primary composites.
Run:  python3 shizukudos/win64/kernel32/gen_unidata.py   (rewrites unidata.h next to this script)
"""
import sys
import unicodedata as ud
from pathlib import Path

GC = ["Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No", "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
      "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co", "Cn"]
BIDI = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF",
        "LRI", "RLI", "FSI", "PDI"]

# attribute word layout (mirrored in nls_core.h)
GC_SHIFT, BIDI_SHIFT, DIG_SHIFT = 0, 5, 10
F_HASDIG, F_WS, F_KATA, F_HIRA, F_HALF, F_FULL, F_IDEO = 1 << 14, 1 << 15, 1 << 16, 1 << 17, 1 << 18, 1 << 19, 1 << 20
SCRIPT_SHIFT = 21          # 0 other, 1 latin, 2 greek, 3 cyrillic


def attr(cp):
    if 0xD800 <= cp <= 0xDFFF:
        gc = "Cs"
    else:
        gc = ud.category(chr(cp))
    ch = chr(cp)
    bidi = ud.bidirectional(ch) if gc != "Cs" else "L"
    if bidi == "":
        bidi = "L" if gc != "Cn" else "L"
    a = GC.index(gc) << GC_SHIFT | BIDI.index(bidi) << BIDI_SHIFT
    d = ud.decimal(ch, None) if gc != "Cs" else None
    if d is not None:
        a |= F_HASDIG | d << DIG_SHIFT
    if cp in (0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000) or 0x2000 <= cp <= 0x200A:
        a |= F_WS
    try:
        name = ud.name(ch)
    except ValueError:
        name = ""
    if name.startswith("HIRAGANA LETTER") or cp in (0x309D, 0x309E):
        a |= F_HIRA
    if name.startswith("KATAKANA") or name.startswith("HALFWIDTH KATAKANA"):
        a |= F_KATA
    if name.startswith("HALFWIDTH"):
        a |= F_HALF
    if name.startswith("FULLWIDTH") or cp == 0x3000:
        a |= F_FULL
    if name.startswith("CJK UNIFIED IDEOGRAPH") or name.startswith("CJK COMPATIBILITY IDEOGRAPH"):
        a |= F_IDEO
    if gc[0] == "L" or gc[0] == "M":
        if name.startswith("LATIN") or name.startswith("FULLWIDTH LATIN"):
            a |= 1 << SCRIPT_SHIFT
        elif name.startswith("GREEK"):
            a |= 2 << SCRIPT_SHIFT
        elif name.startswith("CYRILLIC"):
            a |= 3 << SCRIPT_SHIFT
    return a


def props_runs():
    runs, prev = [], None
    for cp in range(0x110000):
        a = attr(cp)
        if a != prev:
            runs.append((cp, a))
            prev = a
    return runs


def simple_upper(ch):
    u = ch.upper()
    if len(u) == 1:
        return u
    t = ch.title()
    if len(t) == 1 and t != ch and t.upper() != t:            # iota-subscript Greek etc.: UnicodeData maps to the title form
        return t
    return ch


def simple_lower(ch):
    if ch == "İ":
        return "i"                                              # UnicodeData simple mapping; str.lower() yields i + U+0307
    lo = ch.lower()
    return lo if len(lo) == 1 else ch


def case_table():
    rows = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        up, lo = ord(simple_upper(ch)), ord(simple_lower(ch))
        if up != cp or lo != cp:
            rows.append((cp, up - cp, lo - cp))
    return rows


def decomp_table():
    rows, pairs = [], []
    for cp in range(0x80, 0x10000):
        if 0xD800 <= cp <= 0xDFFF or 0xAC00 <= cp <= 0xD7A3:
            continue
        ch = chr(cp)
        nfd = ud.normalize("NFD", ch)
        if nfd == ch or len(nfd) > 3:
            continue
        if any(ord(c) > 0xFFFF for c in nfd):
            continue
        rows.append((cp, [ord(c) for c in nfd]))
        dec = ud.decomposition(ch)
        if dec and not dec.startswith("<"):
            parts = [int(x, 16) for x in dec.split()]
            if len(parts) == 2 and all(p <= 0xFFFF for p in parts) and ud.normalize("NFC", chr(parts[0]) + chr(parts[1])) == ch:
                pairs.append((parts[0], parts[1], cp))
    pairs.sort()
    return rows, pairs


def main():
    out = Path(__file__).resolve().parent / "unidata.h"
    runs = props_runs()
    case = case_table()
    dec, pairs = decomp_table()
    lines = ["/* SPDX-License-Identifier: GPL-2.0-only",
             " * GENERATED by gen_unidata.py from Python unicodedata (Unicode %s). Do not edit." % ud.unidata_version,
             " * Not Windows NLS data: see the header comment of gen_unidata.py. */",
             "#ifndef SHZ_UNIDATA_H", "#define SHZ_UNIDATA_H", "#include <stdint.h>",
             "#define UNI_VERSION \"%s\"" % ud.unidata_version,
             "typedef struct { uint32_t start, attr; } uni_run_t;",
             "typedef struct { uint32_t cp; int32_t up, lo; } uni_case_t;",
             "typedef struct { uint16_t cp; uint16_t n; uint16_t d[3]; } uni_decomp_t;",
             "typedef struct { uint16_t a, b, c; } uni_pair_t;",
             "#define UNI_NRUNS %d" % len(runs), "#define UNI_NCASE %d" % len(case), "#define UNI_NDECOMP %d" % len(dec),
             "#define UNI_NPAIRS %d" % len(pairs), "#ifdef UNI_DEFINE_TABLES",
             "static const uni_run_t uni_runs[UNI_NRUNS] = {"]
    for i in range(0, len(runs), 4):
        lines.append("  " + " ".join("{0x%x,0x%x}," % r for r in runs[i:i + 4]))
    lines += ["};", "static const uni_case_t uni_case[UNI_NCASE] = {"]
    for i in range(0, len(case), 4):
        lines.append("  " + " ".join("{0x%x,%d,%d}," % r for r in case[i:i + 4]))
    lines += ["};", "static const uni_decomp_t uni_decomp[UNI_NDECOMP] = {"]
    for i in range(0, len(dec), 3):
        lines.append("  " + " ".join("{0x%x,%d,{%s}}," % (cp, len(d), ",".join("0x%x" % x for x in (d + [0, 0, 0])[:3])) for cp, d in dec[i:i + 3]))
    lines += ["};", "static const uni_pair_t uni_pairs[UNI_NPAIRS] = {"]
    for i in range(0, len(pairs), 6):
        lines.append("  " + " ".join("{0x%x,0x%x,0x%x}," % p for p in pairs[i:i + 6]))
    lines += ["};", "#endif", "#endif"]
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(runs)} runs, {len(case)} case rows, {len(dec)} decompositions, {len(pairs)} pairs "
          f"(~{(len(runs) * 8 + len(case) * 12 + len(dec) * 10 + len(pairs) * 6) // 1024} KiB)")


if __name__ == "__main__":
    sys.exit(main())
