#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate dlls/gdi32/gdi_font_data.c (the non-ASCII bitmap glyphs of the gdi32 built-in font) from GNU Unifont.

Source: GNU Unifont 18.0.01, unifont-18.0.01.hex.gz, pinned by SHA-256 below (OpenPGP signature by Paul Hardy,
key 95D2E9AB8740D8046387FD151A09227B1F435A33, verified when this pin was made). The font is dual licensed
GPL-2.0-or-later with the GNU font embedding exception / SIL OFL 1.1; see fonts/LICENSE-unifont-18.0.01.txt.
ShizukuOS uses it under the GPL-2.0-or-later option (compatible with gdi32's GPL-2.0-only code).

  gen_font_data.py --hex unifont-18.0.01.hex.gz            # write ../gdi_font_data.c
  gen_font_data.py --hex unifont-18.0.01.hex.gz --check    # regenerate in memory and compare with the committed file
  gen_font_data.py --fetch --check                         # download the pinned file first (network)

Output: one table of ranges (first, last, width 8|16, byte offset) and one byte array. Each glyph is 16 rows; a row is
1 byte (8-wide) or 2 bytes (16-wide, left byte first). Bits are stored LSB = leftmost pixel (Unifont .hex is MSB-left;
the generator reverses), so a row mask has pixel column c in bit c, like the ASCII font8x8 table gdi32 already uses.
"""
import argparse, gzip, hashlib, io, sys, urllib.request
from pathlib import Path

VERSION = "18.0.01"
URL = f"https://unifoundry.com/pub/unifont/unifont-{VERSION}/font-builds/unifont-{VERSION}.hex.gz"
HEX_SHA256 = "e66385c79a0b8b24a466f3129930e08a966a935b4bf3b28c6bb17a9df9bf791d"
OUT = Path(__file__).resolve().parent.parent / "gdi_font_data.c"

# Bounded coverage. ASCII (0x00..0x7f) stays the existing font8x8 VGA font in gdi_font.c.
RANGES = [
    (0x00A0, 0x00FF),   # Latin-1 supplement
    (0x1100, 0x11FF),   # Hangul Jamo
    (0x2010, 0x2027),   # general punctuation (dashes, quotes, bullet, ellipsis)
    (0x2030, 0x203B),   # per mille, primes, reference mark
    (0x2190, 0x2199),   # arrows
    (0x2460, 0x24FF),   # enclosed alphanumerics (circled numbers in Korean UI text)
    (0x2500, 0x257F),   # box drawing
    (0x25A0, 0x25FF),   # geometric shapes
    (0x3000, 0x303F),   # CJK symbols and punctuation
    (0x3131, 0x318E),   # Hangul compatibility Jamo
    (0x3200, 0x321E),   # parenthesized Hangul
    (0x3260, 0x327F),   # circled Hangul
    (0xAC00, 0xD7A3),   # all 11172 modern Hangul syllables
    (0xFF01, 0xFF60),   # fullwidth ASCII forms
    (0xFFE0, 0xFFE6),   # fullwidth signs
]


def load_hex(path):
    raw = Path(path).read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != HEX_SHA256:
        sys.exit(f"{path}: SHA-256 {digest} != pinned {HEX_SHA256}")
    glyphs = {}
    for line in gzip.decompress(raw).decode("ascii").splitlines():
        cp, _, bits = line.partition(":")
        glyphs[int(cp, 16)] = bytes.fromhex(bits)
    return glyphs


def rev8(b):
    return int(f"{b:08b}"[::-1], 2)


def generate(glyphs):
    runs, data = [], bytearray()
    missing = 0
    for first, last in RANGES:
        cur = None
        for cp in range(first, last + 1):
            g = glyphs.get(cp)
            if g is None or len(g) not in (16, 32):
                missing += g is None
                cur = None
                continue
            width = 8 if len(g) == 16 else 16
            if cur and cur[1] == cp - 1 and cur[2] == width:
                cur[1] = cp
            else:
                cur = [cp, cp, width, len(data)]
                runs.append(cur)
            data += bytes(rev8(b) for b in g)
    hangul = sum(r[1] - r[0] + 1 for r in runs if r[0] >= 0xAC00 and r[1] <= 0xD7A3)
    if hangul != 11172:
        sys.exit(f"expected 11172 Hangul syllables, Unifont gave {hangul}")
    out = io.StringIO()
    w = out.write
    w("/* SPDX-License-Identifier: GPL-2.0-or-later WITH Font-exception-2.0 OR OFL-1.1\n")
    w(f" * GENERATED by fonts/gen_font_data.py from GNU Unifont {VERSION} (unifont-{VERSION}.hex.gz,\n")
    w(f" * SHA-256 {HEX_SHA256}). Glyphs: Roman Czyborra, Paul Hardy and the GNU\n")
    w(" * Unifont contributors (https://unifoundry.com/unifont/); see fonts/LICENSE-unifont-18.0.01.txt.\n")
    w(" * Do not edit: regenerate and verify with `gen_font_data.py --fetch --check`. */\n")
    w('#include "gdi_font.h"\n\n')
    w(f"const gdi_font_range_t gdi_font_ranges[{len(runs)}] = {{\n")
    for first, last, width, off in runs:
        w(f"    {{ 0x{first:04X}, 0x{last:04X}, {width}, {off} }},\n")
    w("};\n")
    w(f"const unsigned gdi_font_range_count = {len(runs)};\n\n")
    w(f"const uint8_t gdi_font_bits[{len(data)}] = {{\n")
    for i in range(0, len(data), 32):
        w(",".join(str(b) for b in data[i:i + 32]) + ",\n")
    w("};\n")
    return out.getvalue(), len(runs), len(data), missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hex", help="path to unifont-%s.hex.gz" % VERSION)
    ap.add_argument("--fetch", action="store_true", help="download the pinned hex.gz to a temporary file")
    ap.add_argument("--check", action="store_true", help="compare with the committed output instead of writing it")
    a = ap.parse_args()
    path = a.hex
    if a.fetch:
        import tempfile
        tmp = tempfile.NamedTemporaryFile(suffix=".hex.gz", delete=False)
        tmp.write(urllib.request.urlopen(URL, timeout=60).read())
        tmp.close()
        path = tmp.name
    if not path:
        ap.error("--hex or --fetch is required")
    text, nruns, nbytes, missing = generate(load_hex(path))
    sha = hashlib.sha256(text.encode()).hexdigest()
    if a.check:
        old = OUT.read_text() if OUT.exists() else ""
        if old != text:
            sys.exit(f"MISMATCH: {OUT} differs from regenerated output (sha256 {sha})")
        print(f"OK {OUT.name} sha256 {sha} ranges {nruns} bytes {nbytes} unassigned-in-ranges {missing}")
        return
    OUT.write_text(text)
    print(f"wrote {OUT} sha256 {sha} ranges {nruns} bytes {nbytes} unassigned-in-ranges {missing}")


if __name__ == "__main__":
    main()
