#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Original, deterministic sparse FAT32 fixture. Contains no external files.

Only create() writes: an exclusively created caller-named regular file. It never
formats an existing file/device, invokes a tool, or reads an installed system.
"""
import hashlib
import os
from pathlib import Path
import struct

SECTOR_BYTES = 512
DISK_SECTORS = 131072
DISK_BYTES = DISK_SECTORS * SECTOR_BYTES
PARTITION_LBA, PARTITION_SECTORS = 2048, 129024
RESERVED, FAT_COUNT, FAT_SECTORS, SPC = 32, 2, 1024, 1
DATA_LBA = PARTITION_LBA + RESERVED + FAT_COUNT * FAT_SECTORS
CLUSTER_COUNT = PARTITION_SECTORS - RESERVED - FAT_COUNT * FAT_SECTORS
ROOT_CHAIN = (9, 71, 15)
FILE_CHAIN = tuple(1000 + ((i * 487) % 10007) for i in range(257))
SHORT_NAME, FILE_BYTES = b'NTWBOOT BIN', 131195
EOC = 0x0fffffff


def content():
    return bytes(((i * 29 + (i // 251) * 7 + 0x53) ^ ((i >> 8) & 255)) & 255
                 for i in range(FILE_BYTES))


def cluster_lba(cluster):
    return DATA_LBA + cluster - 2


def _entry(name, cluster, size, attributes=0x26):
    entry = bytearray(32)
    entry[:11], entry[11] = name, attributes
    struct.pack_into('<H', entry, 20, cluster >> 16)
    struct.pack_into('<H', entry, 26, cluster & 0xffff)
    struct.pack_into('<I', entry, 28, size)
    return entry


def sectors():
    """Return only nonzero sectors; absent sectors are deterministic zeros."""
    blocks = {}
    mbr = bytearray(512)
    # No executable bootstrap. Inactive primary0 FAT32 LBA, bounded CHS sentinel.
    mbr[446:462] = struct.pack('<B3sB3sII', 0, b'\xfe\xff\xff', 0x0c,
                               b'\xfe\xff\xff', PARTITION_LBA, PARTITION_SECTORS)
    mbr[510:] = b'\x55\xaa'
    blocks[0] = bytes(mbr)
    boot = bytearray(512)
    boot[:11] = b'\xeb\x58\x90NTWORIG '
    struct.pack_into('<HBHBHHBHHHII', boot, 11, 512, SPC, RESERVED, FAT_COUNT,
                     0, 0, 0xf8, 0, 63, 255, PARTITION_LBA, PARTITION_SECTORS)
    struct.pack_into('<IHHIHH', boot, 36, FAT_SECTORS, 0, 0, ROOT_CHAIN[0], 0xffff, 0xffff)
    boot[64], boot[66] = 0x80, 0x29
    struct.pack_into('<I', boot, 67, 0x4e545746)
    boot[71:82], boot[82:90] = b'NTW FAT LAB', b'FAT32   '
    boot[510:] = b'\x55\xaa'
    blocks[PARTITION_LBA] = bytes(boot)
    entries = {0: 0x0ffffff8, 1: EOC}
    for chain in (ROOT_CHAIN, FILE_CHAIN):
        for index, cluster in enumerate(chain):
            entries[cluster] = chain[index + 1] if index + 1 < len(chain) else EOC
    fat_blocks = {}
    for cluster, value in entries.items():
        sector, offset = divmod(cluster * 4, 512)
        block = fat_blocks.setdefault(sector, bytearray(512))
        struct.pack_into('<I', block, offset, value)
    for copy in range(FAT_COUNT):
        for sector, data in fat_blocks.items():
            blocks[PARTITION_LBA + RESERVED + copy * FAT_SECTORS + sector] = bytes(data)
    for cluster in ROOT_CHAIN[:2]:
        block = bytearray(512)
        for index in range(16):
            block[index * 32] = 0xe5
        if cluster == ROOT_CHAIN[1]:
            block[:32] = _entry(b'NTW FAT LAB', 0, 0, 8)  # volume label, not a file
            block[32:64] = _entry(b'IGNORE  TXT', 0, 0, 0x0f)  # ignored LFN-shaped record
            block[5 * 32:6 * 32] = _entry(SHORT_NAME, FILE_CHAIN[0], FILE_BYTES)
        blocks[cluster_lba(cluster)] = bytes(block)
    last_root = bytearray(512)
    # A matching entry AFTER the directory end must not be interpreted.
    last_root[32:64] = _entry(SHORT_NAME, FILE_CHAIN[0], FILE_BYTES)
    blocks[cluster_lba(ROOT_CHAIN[-1])] = bytes(last_root)
    raw = content()
    for index, cluster in enumerate(FILE_CHAIN):
        part = raw[index * 512:(index + 1) * 512]
        blocks[cluster_lba(cluster)] = part + b'\xcc' * (512 - len(part))
    assert len(FILE_CHAIN) == len(set(FILE_CHAIN)) and not set(FILE_CHAIN) & set(ROOT_CHAIN)
    assert CLUSTER_COUNT >= 65525 and max(FILE_CHAIN) < CLUSTER_COUNT + 2
    assert all(0 <= lba < DISK_SECTORS and len(data) == 512 for lba, data in blocks.items())
    return blocks


def sector(lba):
    if type(lba) is not int or not 0 <= lba < DISK_SECTORS:
        raise ValueError('Synthetic sector is outside the fixed disk')
    return sectors().get(lba, bytes(512))


def metadata(disk_sha256):
    return {'schema': 'shizukudos.synthetic_fat32.v1', 'origin': 'original generated bytes only',
            'disk_bytes': DISK_BYTES, 'disk_sectors': DISK_SECTORS,
            'disk_sha256': disk_sha256, 'partition_index': 0, 'partition_lba': PARTITION_LBA,
            'partition_sectors': PARTITION_SECTORS, 'cluster_count': CLUSTER_COUNT,
            'root_chain': list(ROOT_CHAIN), 'file_chain': list(FILE_CHAIN),
            'short_name': SHORT_NAME.decode('ascii'), 'file_bytes': FILE_BYTES,
            'file_sha256': hashlib.sha256(content()).hexdigest(),
            'windows_files': False, 'boot_code': False}


def create(path):
    """Create a new sparse image exclusively; leave any failed partial for audit."""
    path = Path(path)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, 'wb') as stream:
        stream.truncate(DISK_BYTES)
        for lba, block in sorted(sectors().items()):
            stream.seek(lba * 512)
            if stream.write(block) != 512:
                raise OSError('Short fixture write')
        stream.flush()
        os.fsync(stream.fileno())
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
    return metadata(digest.hexdigest())
