#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Regenerates mathtab.h, the constant tables of math.c, with exact arithmetic (Python integers and decimal at 80
significant digits; pi from Machin's formula). Every double-double entry is (hi, lo) with hi = the double nearest to
the value and lo = the double nearest to value - hi.  Usage: python3 gen_mathtab.py > mathtab.h
"""
from decimal import Decimal, getcontext
from fractions import Fraction

getcontext().prec = 90


def pi_decimal():
    # Machin: pi = 16 atan(1/5) - 4 atan(1/239), with integers scaled by 10^100
    scale = 10 ** 110

    def arctan_inv(n):
        total, term, k, sign = 0, scale // n, 1, 1
        n2 = n * n
        while term:
            total += sign * (term // k)
            term //= n2
            k += 2
            sign = -sign
        return total
    return Decimal(16 * arctan_inv(5) - 4 * arctan_inv(239)) / Decimal(scale)


PI = pi_decimal()
LN2 = Decimal(2).ln()
LN10 = Decimal(10).ln()


def dd(v):
    hi = float(v)
    lo = float(v - Decimal(hi))
    return hi, lo


def trunc_bits(v, bits):
    """v rounded toward zero to `bits` significant bits (as a double, exactly representable)."""
    f = Fraction(v)
    e = 0
    a = abs(f)
    while a >= 2:
        a /= 2
        e += 1
    while a < 1:
        a *= 2
        e -= 1
    scale = Fraction(2) ** (bits - 1 - e)
    t = int(f * scale) / scale
    return float(t)


def h(x):
    return float.hex(x)


def atan_dec(x):
    # atan(x) for |x| <= 1 by atan(x) = 2 atan(x / (1 + sqrt(1 + x^2))) halvings then the series
    x = Decimal(x)
    k = 0
    while abs(x) > Decimal("0.05"):
        x = x / (1 + (1 + x * x).sqrt())
        k += 1
    s, term, n = Decimal(0), x, 1
    x2 = x * x
    while abs(term) > Decimal(10) ** -85:
        s += term / n
        term = -term * x2
        n += 2
    return s * (2 ** k)


def main():
    out = []
    out.append("/* SPDX-License-Identifier: GPL-2.0-only")
    out.append(" * GENERATED by gen_mathtab.py (exact arithmetic: Python integers / decimal, 90 digits). Do not edit. */")
    out.append("#ifndef SHZ_MATHTAB_H")
    out.append("#define SHZ_MATHTAB_H")
    # 2^(j/128)
    out.append("static const double EXP2_TAB[128][2] = {")
    for j in range(128):
        v = (LN2 * j / 128).exp()
        hi, lo = dd(v)
        out.append(f"    {{{h(hi)}, {h(lo)}}},")
    out.append("};")
    # log table: c_j = 1 + j/128 for j = -38 .. 54; inv_j = double nearest to 1/c_j; L_j = -log(inv_j)
    out.append("#define LOG_JMIN (-38)")
    out.append("#define LOG_JMAX 54")
    out.append("static const double LOG_TAB[93][3] = {   /* inv_j, -log(inv_j) hi, lo */")
    for j in range(-38, 55):
        c = Decimal(1) + Decimal(j) / 128
        inv = float(1 / c)
        if j == 0:
            inv = 1.0
        L = -(Decimal(inv).ln())
        hi, lo = dd(L) if j else (0.0, 0.0)
        out.append(f"    {{{h(inv)}, {h(hi)}, {h(lo)}}},")
    out.append("};")
    # atan(k/64), k = 0..64
    out.append("static const double ATAN_TAB[65][2] = {")
    for k in range(65):
        v = atan_dec(Decimal(k) / 64) if k else Decimal(0)
        hi, lo = dd(v)
        out.append(f"    {{{h(hi)}, {h(lo)}}},")
    out.append("};")
    # 1/n! for n = 0..30
    out.append("static const double INV_FACT[31][2] = {")
    f = Decimal(1)
    for n in range(31):
        if n:
            f *= n
        hi, lo = dd(1 / f)
        out.append(f"    {{{h(hi)}, {h(lo)}}},")
    out.append("};")
    # 1/n for n = 1..40 (log1p / atan series)
    out.append("static const double INV_N[41][2] = {")
    out.append("    {0x0p+0, 0x0p+0},")
    for n in range(1, 41):
        hi, lo = dd(Decimal(1) / n)
        out.append(f"    {{{h(hi)}, {h(lo)}}},")
    out.append("};")
    # 2/pi as 32-bit words, most significant first (bits after the binary point)
    two_over_pi = 2 / PI
    frac = Fraction(two_over_pi)
    words = []
    for _ in range(44):
        frac *= 2 ** 32
        w = int(frac)
        words.append(w)
        frac -= w
    out.append("static const uint32_t TWO_OVER_PI[44] = {")
    for i in range(0, 44, 6):
        out.append("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i + 6]) + ",")
    out.append("};")
    # constants
    pio2 = PI / 2
    p1 = trunc_bits(pio2, 33)
    r = pio2 - Decimal(p1)
    p2 = trunc_bits(r, 33)
    r -= Decimal(p2)
    p3 = trunc_bits(r, 33)
    r -= Decimal(p3)
    p4 = float(r)
    ln2_hi = trunc_bits(LN2, 42)
    ln2_lo = float(LN2 - Decimal(ln2_hi))
    l128 = LN2 / 128
    l128_hi = trunc_bits(l128, 34)
    l128_mid = trunc_bits(l128 - Decimal(l128_hi), 34)
    l128_lo = float(l128 - Decimal(l128_hi) - Decimal(l128_mid))
    consts = {
        "PIO2_1": p1, "PIO2_2": p2, "PIO2_3": p3, "PIO2_4": p4,
        "LN2_HI": ln2_hi, "LN2_LO": ln2_lo,
        "LN2_128_HI": l128_hi, "LN2_128_MID": l128_mid, "LN2_128_LO": l128_lo,
        "INV_LN2_128": float(128 / LN2), "TWO_OVER_PI_D": float(2 / PI),
    }
    for name, v in consts.items():
        out.append(f"#define {name} {h(v)}")
    for name, v in (("PI", PI), ("PIO2", PI / 2), ("PIO4", PI / 4), ("LN2", LN2), ("LN10", LN10), ("INV_LN2", 1 / LN2),
                    ("INV_LN10", 1 / LN10), ("LOG10_2", LN2 / LN10), ("SQRT_PI", PI.sqrt()), ("TWO_OVER_SQRT_PI", 2 / PI.sqrt()),
                    ("LN_SQRT_2PI", (2 * PI).sqrt().ln()), ("LN_PI", PI.ln())):
        hi, lo = dd(v)
        out.append(f"#define C_{name}_HI {h(hi)}")
        out.append(f"#define C_{name}_LO {h(lo)}")
    out.append("#endif")
    print("\n".join(out))


if __name__ == "__main__":
    main()
