#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Regenerates wctype_tab.h: the ctype class of every UTF-16 code unit of the Basic Multilingual Plane, derived from the
Unicode general categories of Python's unicodedata (Unicode database of the running interpreter), as compact runs.

The Shizuku UCRT has no Windows NLS tables (GetStringTypeW), so its "C"-locale iswctype() classifies from Unicode:
Lu -> upper|alpha, Ll -> lower|alpha, Lt/Lm/Lo -> alpha, Nd -> digit, Zs -> space|blank (plus the C0 spaces),
Zl/Zp -> space, P*/S*/No -> punct, Cc -> control, ASCII hex digits -> xdigit. Documented in docs/shizukudos10/CRT.md.
Usage: python3 gen_wctype.py > wctype_tab.h
"""
import unicodedata

UPPER, LOWER, DIGIT, SPACE, PUNCT, CONTROL, BLANK, HEX, ALPHA = 0x1, 0x2, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80, 0x100


def cls(cp):
    if 0xD800 <= cp <= 0xDFFF:
        return 0
    c = chr(cp)
    cat = unicodedata.category(c)
    m = 0
    if cat == "Lu":
        m |= UPPER | ALPHA
    elif cat == "Ll":
        m |= LOWER | ALPHA
    elif cat in ("Lt", "Lm", "Lo"):
        m |= ALPHA
    elif cat == "Nd":
        m |= DIGIT
    elif cat == "Zs":
        m |= SPACE | BLANK
    elif cat in ("Zl", "Zp"):
        m |= SPACE
    elif cat[0] in "PS" or cat == "No":
        m |= PUNCT
    elif cat == "Cc":
        m |= CONTROL
    if cp in (0x09, 0x0A, 0x0B, 0x0C, 0x0D):
        m |= SPACE
    if cp == 0x09:
        m |= BLANK
    if chr(cp) in "0123456789abcdefABCDEF":
        m |= HEX
    return m


def main():
    runs = []
    cur, start = cls(0), 0
    for cp in range(1, 0x10000):
        m = cls(cp)
        if m != cur:
            runs.append((start, cp - 1, cur))
            cur, start = m, cp
    runs.append((start, 0xFFFF, cur))
    print("/* SPDX-License-Identifier: GPL-2.0-only")
    print(f" * GENERATED by gen_wctype.py from Unicode {unicodedata.unidata_version} (Python unicodedata). Do not edit.")
    print(" * ctype class runs of the BMP: code units lo..hi have class mask m (_UPPER 1 .. _ALPHA 0x100). */")
    print("#ifndef SHZ_WCTYPE_TAB_H")
    print("#define SHZ_WCTYPE_TAB_H")
    print("static const struct { unsigned short lo, hi, m; } wctype_runs[] = {")
    for lo, hi, m in runs:
        print(f"    {{0x{lo:04x}, 0x{hi:04x}, 0x{m:03x}}},")
    print("};")
    print("#endif")


if __name__ == "__main__":
    main()
