# SPDX-License-Identifier: GPL-2.0-only
# CMake toolchain for WebKit (WTF/JavaScriptCore) on the ShizukuDOS Kernel64 Win64 runtime (docs/shizukudos10/WEBKIT.md).
# The compiler, sysroot and C++ runtime are the shared WebKit toolchain generated by webkit/deps/toolchain.py (clang 18
# for x86_64-w64-mingw32, mingw-w64 v13 built for the UCRT, libc++ 18 DLLs); this file includes it and adds what the
# JavaScriptCore build needs. build.py passes:
#   SHZ_WEBKIT_TOOLCHAIN  build/shizukudos/webkit/toolchain/toolchain.cmake
#   SHZ_ICU_PREFIX        the static Win64 ICU
#   SHZ_LIBALIAS          mixed-case library names WebKit links (-lDbgHelp, -lWinmm) mapped to the sysroot's
# try_compile projects (compiler checks) do not see -D cache variables: pass them on, with the environment as the
# fallback build.py also sets.
foreach(_v SHZ_WEBKIT_TOOLCHAIN SHZ_ICU_PREFIX SHZ_LIBALIAS)
    if (NOT DEFINED ${_v})
        set(${_v} "$ENV{${_v}}")
    endif ()
endforeach ()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES SHZ_WEBKIT_TOOLCHAIN SHZ_ICU_PREFIX SHZ_LIBALIAS)
include(${SHZ_WEBKIT_TOOLCHAIN})
list(APPEND CMAKE_FIND_ROOT_PATH ${SHZ_ICU_PREFIX})
set(_shz_ldflags "-L${SHZ_LIBALIAS} -Wl,--no-insert-timestamp")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_shz_ldflags}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_shz_ldflags}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_shz_ldflags}")
