# SPDX-License-Identifier: GPL-2.0-only
# CMake toolchain for WebKit (WTF/JavaScriptCore) on the ShizukuDOS Kernel64 Win64 runtime (docs/shizukudos10/WEBKIT.md).
# The compiler, sysroot and C++ runtime are the shared WebKit toolchain generated by webkit/deps/toolchain.py (clang 18
# for x86_64-w64-mingw32, mingw-w64 v13 built for the UCRT, libc++ 18 DLLs); this file includes it and adds what the
# JavaScriptCore build needs. build.py passes:
#   SHZ_WEBKIT_TOOLCHAIN  build/shizukudos/webkit/toolchain/toolchain.cmake
#   SHZ_ICU_PREFIX        the static Win64 ICU
#   SHZ_LIBALIAS          mixed-case library names WebKit links (-lDbgHelp, -lWinmm) mapped to the sysroot's
include(${SHZ_WEBKIT_TOOLCHAIN})
list(APPEND CMAKE_FIND_ROOT_PATH ${SHZ_ICU_PREFIX})
set(_shz_ldflags "-L${SHZ_LIBALIAS} -Wl,--no-insert-timestamp")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_shz_ldflags}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_shz_ldflags}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_shz_ldflags}")
