/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef SHZ_SETUP_UI_STRINGS_H
#define SHZ_SETUP_UI_STRINGS_H
#include <stdint.h>
#include <windows.h>
enum setup_string {
 UI_WELCOME,UI_WELCOME_BODY,UI_TARGET,UI_TARGET_BODY,UI_SUMMARY,UI_PROGRESS,UI_COMPLETE,UI_FAILURE,
 UI_CONTINUE,UI_BACK,UI_EXIT,UI_ERASE_INSTALL,UI_CANCEL,UI_DETAILS,UI_HIDE_DETAILS,UI_RESTART,UI_SHUTDOWN,
 UI_SCANNING,UI_NO_TARGET,UI_REQUIRED,UI_DESTRUCTIVE,UI_BOOT_CHANGE,UI_NO_OTHER_DISKS,UI_PREFLIGHT,
 UI_COPY_ESP,UI_VERIFY_ESP,UI_COPY_SYSTEM,UI_VERIFY_SYSTEM,UI_PARTITIONS,UI_FINALIZE,UI_NONCANCEL,
 UI_CANCEL_REQUESTED,UI_PARTIAL,UI_REMOVE_MEDIA,UI_ACCOUNT_NEXT,UI_TARGET_CHANGED,UI_SELECT_EXPLICIT,
 UI_US_KEYBOARD,UI_LANGUAGE,UI_IMAGE,UI_BYTES,UI_FILES,UI_SAVE_LOG,UI_LOG_SAVED,UI_LOG_FAILED,
 UI_CANCEL_SAFE,UI_FIXED,UI_REMOVABLE,UI_DISK_RO,UI_DISK_PARTITION,UI_DISK_SECTOR,UI_DISK_REMOVABLE_UNSUPPORTED,UI_DISK_SPACE,UI_DISK_EXCLUDED,UI_VERIFIED_FILES,UI_COUNT
};
const WCHAR *setup_string(uint32_t language,enum setup_string id);
#endif
