# SPDX-License-Identifier: GPL-2.0-only
"""Platform-independent verification of a finished DOS16 conformance run.

The same FAT12 image and the same expectations apply whether the guest ran on a
real BIOS (QEMU/SeaBIOS = the CSM profile) or under the Shizuku Supervisor's
virtual Real Mode. Every check reads guest-generated bytes from the disk image
or guest memory; console text is only cross-checked.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fatimg  # noqa: E402
import ints  # noqa: E402


def _check(name, ok, detail=""):
    return {"check": name, "status": "PASS" if ok else "FAIL", "detail": detail}


def verify_disk(disk):
    image = fatimg.partition_spec(disk)
    checks = []
    result = fatimg.read_bytes(image, "RESULT.TXT")
    text = result.decode("ascii", "replace").replace("\r\n", "\n") if result else ""
    checks.append(_check("RESULT.TXT exists", result is not None))
    lines = [l.strip() for l in text.splitlines() if l.strip()]

    m = re.search(r"^T_MODE PASS CR0=([0-9A-F]{8}) CR4=([0-9A-F]{8}) EFL=([0-9A-F]{8})$", text, re.M)
    checks.append(_check("T_MODE real mode (CR0.PE=0, EFLAGS.VM=0)", bool(m) and not int(m.group(1), 16) & 1
                         and not int(m.group(3), 16) & 0x20000,
                         m.group(0) if m else "missing"))
    m = re.search(r"^T_BIOS PASS CONV=([0-9A-F]{8}) EXT=([0-9A-F]{8}) EQUIP=([0-9A-F]{8})$", text, re.M)
    checks.append(_check("T_BIOS platform contract", bool(m) and 480 <= int(m.group(1), 16) <= 640,
                         m.group(0) if m else "missing"))
    checks.append(_check("T_COM DOS services", "T_COM PASS" in lines))
    checks.append(_check("T_EXE MZ program", "T_EXE PASS argc=3" in lines))
    checks.append(_check("T_EXE exit code 42 seen by batch file", "T_EXE_EXITCODE PASS" in lines))
    checks.append(_check("batch completed", lines[-1:] == ["DONE"]))

    out = fatimg.read_bytes(image, "T_COM.OUT")
    checks.append(_check("T_COM.OUT contents", out == b"SHZ-COM-FILE-OK 0123456789ABCDEF\r\n",
                         repr(out)[:60]))
    exe_out = fatimg.read_bytes(image, "T_EXE.OUT")
    expected = b"".join(b"line %03d SHZ-EXE\r\n" % i for i in range(400))
    checks.append(_check("T_EXE.OUT 400 lines byte-exact", exe_out == expected,
                         f"{len(exe_out or b'')} bytes"))
    return checks, text


def verify_ints(disk, image, run_utc=None):
    """T_INTS (dual image only): RESULT.TXT line plus every host-side INTS.TXT check (see ints.py).

    `image` is the pristine disk image the run started from; `disk` the disk after the run.
    Returns (checks, index-of-INTS.TXT or None)."""
    spec = fatimg.partition_spec(disk)
    result = fatimg.read_bytes(spec, "RESULT.TXT") or b""
    lines = [l.strip() for l in result.decode("ascii", "replace").splitlines() if l.strip()]
    checks = [_check("T_INTS guest verdict in RESULT.TXT", "T_INTS PASS" in lines,
                     next((l for l in lines if l.startswith("T_INTS")), "missing"))]
    raw = fatimg.read_bytes(spec, "INTS.TXT")
    checks.append(_check("INTS.TXT exists", raw is not None, f"{len(raw or b'')} bytes"))
    if raw is None:
        return checks, None
    more, ix = ints.verify(raw.decode("ascii", "replace"), Path(image).read_bytes(), Path(disk).read_bytes(),
                           run_utc=run_utc)
    return checks + more, ix


def verify_screen(lines):
    joined = "\n".join(lines)
    return [_check("kernel banner shows ShizukuDOS branding", "ShizukuDOS 10.0-dev DOS16" in joined)]


def overall(checks):
    return "PASS" if checks and all(c["status"] == "PASS" for c in checks) else "FAIL"
