# SPDX-License-Identifier: GPL-2.0-only
"""custody-b10: original-userland observation honours cancel/expiry mid-read.

Real LeaseUnion (real read leases), real native_epoch_host.Attempt held over
tiny owned config/ROM files (generated by prepare_original_intent as in
test_original_epoch_generated_manifest), and a small fake-FAT observer that
drives the callback exactly as the FAT reader does (one call per read).
No QEMU, no Microsoft media. Lease/ownership failures surface as errors and
are never counted as passes.
"""
import hashlib
import os
from pathlib import Path
import sys
import time
import unittest
from unittest.mock import patch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import test_original_epoch_generated_manifest as gen  # noqa: E402

guardian = gen.guardian
READS = 200
FIELDS = ('observed_windows_path', 'observed_members', 'boot_sectors')


class ObservationDeadline(gen.GeneratedOriginalEpochManifest):
    def setUp(self):
        super().setUp()
        _, self.ctx = self.generate('obs')
        data = os.urandom(8192)
        self.profile = {'observed_windows_path': 'C:\\WINDOWS', 'observed_members': [1], 'boot_sectors': [2]}
        self.disk = self.write('OBS.IMG', data)
        self.proof = {'source_disk': self.disk, 'observed_windows_path': 'C:\\WINDOWS'}
        self.calls = 0
        self.producers = (self.write('o.py', b'#1\n'), self.write('f.py', b'#2\n'))

    def run_obs(self, per_read=0.0, context='ctx', before=None):
        outer = self
        class Observer:
            def observe(self, fd, size, win, constructor, check):
                for _ in range(READS):
                    outer.calls += 1; check()
                    if per_read: time.sleep(per_read)
                return {n: outer.profile[n] for n in FIELDS}
        with patch.object(guardian, 'admitted_module', side_effect=lambda n, row, u: Observer() if n.endswith('observer') else object()):
            return guardian.check_original_observation(
                self.profile, self.proof, self.producers, self.union, self.ctx if context == 'ctx' else context)

    def test_positive_future_deadline_and_none_control(self):
        self.assertIsNone(self.run_obs())
        self.assertEqual(self.calls, READS)  # every FAT read ran the guard
        self.calls = 0
        self.assertIsNone(self.run_obs(context=None))
        self.assertEqual(self.calls, READS)
        self.assertTrue(all(r.get('full_SHA_admitted', True) for r in self.union.rows.values()))

    def test_expired_deadline_raises_before_inventory_completes_no_child(self):
        a = self.ctx['attempt']
        d = time.monotonic_ns() + 150_000_000
        a.original_deadline_ns = a._deadline = d   # same retained deadline, shortened for the test clock
        a.policy = a.expected.policy(a.nonce, d); os.close(a.policy_fd)  # policy re-seal is not part of this test
        a.policy_fd = None
        with self.assertRaises(ValueError):
            self.run_obs(per_read=0.02)
        self.assertLess(self.calls, READS)
        self.assertIsNone(a.owner)   # no child bound/launched

    def test_cancel_raised_by_real_outer_guard_before_inventory_completes(self):
        seen = []
        def cancel():
            seen.append(time.monotonic())
            if len(seen) >= 3: raise ValueError('cancelled')
        self.ctx['guard'] = cancel
        t0 = time.monotonic()
        with self.assertRaises(ValueError):
            self.run_obs(per_read=0.06)
        self.assertLess(self.calls, READS)
        self.assertGreaterEqual(len(seen), 3)
        gaps = [b - a for a, b in zip(seen, seen[1:])]
        self.assertTrue(all(g < 0.5 for g in gaps), gaps)  # outer guard cadence ~SWEEP_SECONDS

    def test_deadline_not_renewable(self):
        a = self.ctx['attempt']
        original = a.original_deadline_ns
        outer = self
        class Observer:
            def observe(self, fd, size, win, constructor, check):
                check(); a.original_deadline_ns = original + 10**12; check()
                return {n: outer.profile[n] for n in FIELDS}
        with patch.object(guardian, 'admitted_module', side_effect=lambda n, row, u: Observer() if n.endswith('observer') else object()):
            with self.assertRaises(ValueError):
                guardian.check_original_observation(self.profile, self.proof, self.producers, self.union, self.ctx)

    def test_source_closure_retained_and_mismatch_refused(self):
        before = dict(self.union.rows)
        self.run_obs()
        self.assertEqual(set(self.union.rows), set(before) | {self.disk['path']})
        with self.assertRaises(ValueError):
            self._mismatch(dict(self.profile, boot_sectors=[3]))

    def _mismatch(self, p):
        class Observer:
            def observe(s, fd, size, win, constructor, check):
                return {'observed_windows_path': 'C:\\WINDOWS', 'observed_members': [1], 'boot_sectors': [2]}
        with patch.object(guardian, 'admitted_module', side_effect=lambda n, row, u: Observer() if n.endswith('observer') else object()):
            guardian.check_original_observation(p, self.proof, self.producers, self.union, self.ctx)


for _n in ('test_generated_manifest_admitted_with_integer_roles', 'test_generated_vga_only_manifest_admitted',
           'test_tampered_or_stale_generated_variants_refused'):
    setattr(ObservationDeadline, _n, None)

if __name__ == '__main__':
    unittest.main()
