#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate kernel64/apiset_table.h from kernel64/apiset_contracts.txt (the API-set contract table of the Kernel64
PE32+ loader; the row format is documented at the top of the source table).

  python3 shizukudos/win64/tools/gen_apiset_table.py            write the header
  python3 shizukudos/win64/tools/gen_apiset_table.py --check    fail when the checked-in header is stale

The same parser is imported by the host tools (import_coverage.py, the load simulator's tests) so there is exactly one
reading of the table.
"""
import argparse
import re
import sys
from pathlib import Path

K64 = Path(__file__).resolve().parents[2] / "kernel64"
SOURCE = K64 / "apiset_contracts.txt"
HEADER = K64 / "apiset_table.h"
NAME = re.compile(r"^((?:api|ext)-[a-z0-9-]+-l\d+)-(\d+)-(\d+)$")
DLL = re.compile(r"^[a-z0-9_.-]+\.dll$")


class Row:
    def __init__(self, contract, major, minor, windows_host, host, note, line):
        self.contract, self.major, self.minor = contract, major, minor
        self.windows_host, self.host, self.note, self.line = windows_host, host, note, line

    @property
    def name(self):
        return f"{self.contract}-{self.major}-{self.minor}"


def parse(path=SOURCE):
    """-> list of Row sorted by (contract, major, minor). Raises ValueError on a malformed table."""
    providers, rows, seen = {}, [], set()
    for n, raw in enumerate(path.read_text().splitlines(), 1):
        text, _, note = raw.partition("#")
        f = text.split()
        if not f:
            continue
        if f[0] == "@provider":
            if len(f) != 3 or not DLL.match(f[1]) or not DLL.match(f[2]):
                raise ValueError(f"{path.name}:{n}: @provider <windows dll> <shizuku dll>")
            providers[f[1]] = f[2]
            continue
        if len(f) not in (2, 3):
            raise ValueError(f"{path.name}:{n}: expected <contract> <windows host> [<shizuku host>]")
        m = NAME.match(f[0])
        if not m or f[0] != f[0].lower():
            raise ValueError(f"{path.name}:{n}: bad contract name {f[0]!r} (lowercase api-/ext- name ending in -lL-M-m)")
        if len(m.group(1)) > 95:
            raise ValueError(f"{path.name}:{n}: contract name too long")
        for d in f[1:]:
            if not DLL.match(d) or len(d) > 47:
                raise ValueError(f"{path.name}:{n}: bad DLL name {d!r}")
        key = (m.group(1), int(m.group(2)), int(m.group(3)))
        if key in seen:
            raise ValueError(f"{path.name}:{n}: duplicate row {f[0]}")
        seen.add(key)
        host = f[2] if len(f) == 3 else providers.get(f[1], f[1])
        rows.append(Row(key[0], key[1], key[2], f[1], host, note.strip(), n))
    rows.sort(key=lambda r: (r.contract, r.major, r.minor))
    return rows


SUFFIX = re.compile(r"^(.{5,}-l\d{1,5})-(\d{1,5})-(\d{1,5})$", re.S)
OK, UNKNOWN, VERSION, BAD_NAME, NOT_APISET = 1, -1, -2, -3, 0


def lookup(rows, name):
    """Python reading of kernel64/apiset.c apiset_lookup(): -> (result, row or None). The host tests check that both
    agree on every table row, every name the target trees import and a fuzz corpus."""
    n = "".join(chr(ord(ch) + 32) if "A" <= ch <= "Z" else ch for ch in name)      # ASCII-only folding, like the C code
    if not n.startswith(("api-", "ext-")):
        return NOT_APISET, None
    if len(n) >= 127:
        return BAD_NAME, None
    if len(n) > 4 and n.endswith(".dll"):
        n = n[:-4]
    m = SUFFIX.match(n)
    if not m:
        return BAD_NAME, None
    contract, major, minor = m.group(1), int(m.group(2)), int(m.group(3))
    cands = [r for r in rows if r.contract == contract]
    if not cands:
        return UNKNOWN, None
    best = cands[-1]
    return (VERSION if (best.major, best.minor) < (major, minor) else OK), best


def render(rows):
    out = ["/* SPDX-License-Identifier: GPL-2.0-only",
           " * GENERATED by shizukudos/win64/tools/gen_apiset_table.py from kernel64/apiset_contracts.txt. Do not edit.",
           " * {contract (with level), major, minor, Windows host, Shizuku host}, sorted by contract then version:",
           " * kernel64/apiset.c binary-searches it. */",
           "#ifndef K64_APISET_TABLE_H", "#define K64_APISET_TABLE_H", "#include \"apiset.h\"", "",
           "static const apiset_entry_t apiset_table[] = {"]
    for r in rows:
        out.append(f'    {{"{r.contract}", {r.major}, {r.minor}, "{r.windows_host}", "{r.host}"}},')
    out += ["};", f"#define APISET_TABLE_COUNT {len(rows)}u", "#endif", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify that the checked-in header matches the table")
    args = ap.parse_args()
    rows = parse()
    text = render(rows)
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != text:
            print(f"{HEADER} is stale: run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{HEADER.name} is current ({len(rows)} contracts)")
        return 0
    HEADER.write_text(text)
    print(f"wrote {HEADER} ({len(rows)} contracts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
