/* SPDX-License-Identifier: GPL-2.0-only
 * Build-time proof that the driver host's ABI numbers (kernel64/ntddk_abi.h) match
 * Microsoft's real <ddk/wdm.h> on x64. Compiled, not run, with mingw-w64: any mismatch is a
 * failed _Static_assert that stops the build. kernel64/ntddk.h asserts the SAME numbers
 * against the host's own structs (checked by the Linux kernel build), so passing both sides
 * means the host and Windows agree field-for-field. Nothing about the ABI is assumed.
 *
 *   x86_64-w64-mingw32-gcc -fsyntax-only -D_WIN64 -I<ddk> -I<kernel64> ntddk_abi_check.c
 */
#include <ddk/wdm.h>
#include <ddk/ntddk.h>
#include <stddef.h>
#include "ntddk_abi.h"

#define CHK(expr, off) _Static_assert(offsetof expr == (off), #expr " != " #off)
#define CHKSZ(t, sz) _Static_assert(sizeof(t) == (sz), #t " size != " #sz)

CHKSZ(IRP, SZ_IRP);
CHK((IRP, MdlAddress), OFF_IRP_MDLADDRESS);
CHK((IRP, Flags), OFF_IRP_FLAGS);
CHK((IRP, AssociatedIrp.SystemBuffer), OFF_IRP_SYSTEMBUFFER);
CHK((IRP, IoStatus), OFF_IRP_IOSTATUS);
CHK((IRP, IoStatus.Information), OFF_IRP_IOSTATUS_INFO);
CHK((IRP, RequestorMode), OFF_IRP_REQUESTORMODE);
CHK((IRP, StackCount), OFF_IRP_STACKCOUNT);
CHK((IRP, CurrentLocation), OFF_IRP_CURRENTLOCATION);
CHK((IRP, UserIosb), OFF_IRP_USERIOSB);
CHK((IRP, UserEvent), OFF_IRP_USEREVENT);
CHK((IRP, CancelRoutine), OFF_IRP_CANCELROUTINE);
CHK((IRP, UserBuffer), OFF_IRP_USERBUFFER);
CHK((IRP, Tail.Overlay.Thread), OFF_IRP_TAIL_THREAD);
CHK((IRP, Tail.Overlay.ListEntry), OFF_IRP_TAIL_LISTENTRY);
CHK((IRP, Tail.Overlay.CurrentStackLocation), OFF_IRP_TAIL_CURRENTSTACK);

CHKSZ(IO_STACK_LOCATION, SZ_STK);
CHK((IO_STACK_LOCATION, Parameters), OFF_STK_PARAMETERS);
CHK((IO_STACK_LOCATION, Parameters.DeviceIoControl.OutputBufferLength), OFF_STK_IOCTL_OUTLEN);
CHK((IO_STACK_LOCATION, Parameters.DeviceIoControl.InputBufferLength), OFF_STK_IOCTL_INLEN);
CHK((IO_STACK_LOCATION, Parameters.DeviceIoControl.IoControlCode), OFF_STK_IOCTL_CODE);
CHK((IO_STACK_LOCATION, Parameters.DeviceIoControl.Type3InputBuffer), OFF_STK_IOCTL_TYPE3);
CHK((IO_STACK_LOCATION, Parameters.Read.Length), OFF_STK_READ_LENGTH);
CHK((IO_STACK_LOCATION, Parameters.Read.ByteOffset), OFF_STK_READ_BYTEOFFSET);
CHK((IO_STACK_LOCATION, DeviceObject), OFF_STK_DEVICEOBJECT);
CHK((IO_STACK_LOCATION, FileObject), OFF_STK_FILEOBJECT);
CHK((IO_STACK_LOCATION, CompletionRoutine), OFF_STK_COMPLETIONROUTINE);
CHK((IO_STACK_LOCATION, Context), OFF_STK_CONTEXT);

CHKSZ(DRIVER_OBJECT, SZ_DRV);
CHK((DRIVER_OBJECT, DeviceObject), OFF_DRV_DEVICEOBJECT);
CHK((DRIVER_OBJECT, DriverExtension), OFF_DRV_DRIVEREXTENSION);
CHK((DRIVER_OBJECT, DriverName), OFF_DRV_DRIVERNAME);
CHK((DRIVER_OBJECT, DriverInit), OFF_DRV_DRIVERINIT);
CHK((DRIVER_OBJECT, DriverStartIo), OFF_DRV_DRIVERSTARTIO);
CHK((DRIVER_OBJECT, DriverUnload), OFF_DRV_DRIVERUNLOAD);
CHK((DRIVER_OBJECT, MajorFunction), OFF_DRV_MAJORFUNCTION);

CHKSZ(DEVICE_OBJECT, SZ_DEV);
CHK((DEVICE_OBJECT, DriverObject), OFF_DEV_DRIVEROBJECT);
CHK((DEVICE_OBJECT, NextDevice), OFF_DEV_NEXTDEVICE);
CHK((DEVICE_OBJECT, AttachedDevice), OFF_DEV_ATTACHEDDEVICE);
CHK((DEVICE_OBJECT, Flags), OFF_DEV_FLAGS);
CHK((DEVICE_OBJECT, Characteristics), OFF_DEV_CHARACTERISTICS);
CHK((DEVICE_OBJECT, DeviceExtension), OFF_DEV_DEVICEEXTENSION);
CHK((DEVICE_OBJECT, DeviceType), OFF_DEV_DEVICETYPE);
CHK((DEVICE_OBJECT, StackSize), OFF_DEV_STACKSIZE);

CHK((DEVICE_OBJECT, Queue), OFF_DEV_QUEUE);
CHK((DEVICE_OBJECT, AlignmentRequirement), OFF_DEV_ALIGNMENT);
CHK((DEVICE_OBJECT, DeviceQueue), OFF_DEV_DEVICEQUEUE);
CHK((DEVICE_OBJECT, Dpc), OFF_DEV_DPC);
CHK((DEVICE_OBJECT, ActiveThreadCount), OFF_DEV_ACTIVETHREADS);
CHK((DEVICE_OBJECT, SecurityDescriptor), OFF_DEV_SECURITY);
CHK((DEVICE_OBJECT, DeviceLock), OFF_DEV_DEVICELOCK);
CHK((DEVICE_OBJECT, SectorSize), OFF_DEV_SECTORSIZE);
CHK((DEVICE_OBJECT, DeviceObjectExtension), OFF_DEV_DEVOBJEXT);
CHKSZ(KDEVICE_QUEUE, SZ_KDEVICE_QUEUE);
CHK((KDEVICE_QUEUE, Lock), 0x18);
CHK((KDEVICE_QUEUE, Busy), 0x20);
CHKSZ(KDEVICE_QUEUE_ENTRY, SZ_KDEVICE_QUEUE_ENTRY);
CHK((IRP, Tail.Overlay.DeviceQueueEntry), OFF_IRP_TAIL_DEVQUEUE);
CHK((IO_STACK_LOCATION, Parameters.Power.Type), OFF_STK_POWER_TYPE);
CHK((IO_STACK_LOCATION, Parameters.Power.State), OFF_STK_POWER_STATE);
CHK((IO_STACK_LOCATION, Parameters.Power.ShutdownType), OFF_STK_POWER_SHUTDOWN);
CHK((IO_STACK_LOCATION, Parameters.StartDevice.AllocatedResourcesTranslated), OFF_STK_START_TRANSLATED);
CHK((IO_STACK_LOCATION, Parameters.QueryInterface.Version), OFF_STK_QI_VERSION);
CHK((IO_STACK_LOCATION, Parameters.QueryInterface.InterfaceSpecificData), OFF_STK_QI_SPECIFIC);
CHKSZ(DRIVER_EXTENSION, SZ_DRIVER_EXTENSION);
CHKSZ(CM_PARTIAL_RESOURCE_DESCRIPTOR, SZ_CM_PARTIAL_RESOURCE_DESCRIPTOR);
CHKSZ(CM_PARTIAL_RESOURCE_LIST, SZ_CM_PARTIAL_RESOURCE_LIST);
CHKSZ(CM_FULL_RESOURCE_DESCRIPTOR, SZ_CM_FULL_RESOURCE_DESCRIPTOR);
CHKSZ(CM_RESOURCE_LIST, SZ_CM_RESOURCE_LIST);
CHK((CM_PARTIAL_RESOURCE_DESCRIPTOR, u.Generic.Length), 0x0c);
CHK((CM_PARTIAL_RESOURCE_DESCRIPTOR, u.Interrupt.Vector), 0x08);
CHKSZ(IO_RESOURCE_DESCRIPTOR, SZ_IO_RESOURCE_DESCRIPTOR);
CHKSZ(IO_RESOURCE_LIST, SZ_IO_RESOURCE_LIST);
CHKSZ(IO_RESOURCE_REQUIREMENTS_LIST, SZ_IO_RESOURCE_REQUIREMENTS_LIST);
CHKSZ(RTL_QUERY_REGISTRY_TABLE, SZ_RTL_QUERY_REGISTRY_TABLE);
CHK((RTL_QUERY_REGISTRY_TABLE, DefaultLength), 0x30);
CHKSZ(IO_REMOVE_LOCK_COMMON_BLOCK, SZ_IO_REMOVE_LOCK_COMMON);
CHK((IO_REMOVE_LOCK, Common.IoCount), 0x04);
CHK((IO_REMOVE_LOCK, Common.RemoveEvent), 0x08);
CHKSZ(NPAGED_LOOKASIDE_LIST, SZ_NPAGED_LOOKASIDE_LIST);
CHK((GENERAL_LOOKASIDE, Allocate), OFF_LOOKASIDE_ALLOCATE);
CHK((GENERAL_LOOKASIDE, Free), OFF_LOOKASIDE_FREE);
CHK((GENERAL_LOOKASIDE, Depth), OFF_LOOKASIDE_DEPTH);
CHK((GENERAL_LOOKASIDE, Tag), OFF_LOOKASIDE_TAG);
CHK((GENERAL_LOOKASIDE, Size), OFF_LOOKASIDE_SIZE);
CHKSZ(ERESOURCE, SZ_ERESOURCE);
CHKSZ(FAST_MUTEX, SZ_FAST_MUTEX);
CHKSZ(KGUARDED_MUTEX, SZ_KGUARDED_MUTEX);
CHKSZ(WORK_QUEUE_ITEM, SZ_WORK_QUEUE_ITEM);
CHK((WORK_QUEUE_ITEM, WorkerRoutine), OFF_WORK_QUEUE_ITEM_ROUTINE);
CHKSZ(DMA_ADAPTER, SZ_DMA_ADAPTER);
CHKSZ(DMA_OPERATIONS, SZ_DMA_OPERATIONS);
CHKSZ(DEVICE_DESCRIPTION, SZ_DEVICE_DESCRIPTION);
CHK((DEVICE_DESCRIPTION, MaximumLength), 0x20);
CHK((DEVICE_DESCRIPTION, ScatterGather), 0x05);
CHK((DEVICE_DESCRIPTION, Dma64BitAddresses), 0x0b);
CHKSZ(SCATTER_GATHER_LIST, SZ_SCATTER_GATHER_LIST);
CHKSZ(SCATTER_GATHER_ELEMENT, SZ_SCATTER_GATHER_ELEMENT);
CHKSZ(IO_ERROR_LOG_PACKET, SZ_IO_ERROR_LOG_PACKET);
CHK((IO_ERROR_LOG_PACKET, ErrorCode), OFF_ERRLOG_ERRORCODE);
CHK((IO_ERROR_LOG_PACKET, FinalStatus), OFF_ERRLOG_FINALSTATUS);
CHK((IO_ERROR_LOG_PACKET, DumpData), OFF_ERRLOG_DUMPDATA);
CHKSZ(CONFIGURATION_INFORMATION, SZ_CONFIGURATION_INFORMATION);
CHK((KEY_VALUE_FULL_INFORMATION, Name), OFF_KEY_VALUE_FULL_NAME);
CHK((KEY_BASIC_INFORMATION, Name), OFF_KEY_BASIC_NAME);
CHK((KEY_NODE_INFORMATION, Name), OFF_KEY_NODE_NAME);
CHKSZ(KEY_FULL_INFORMATION, SZ_KEY_FULL_INFORMATION);
CHKSZ(DEVICE_INTERFACE_CHANGE_NOTIFICATION, SZ_DEVICE_INTERFACE_CHANGE_NOTIFICATION);
CHKSZ(RTL_OSVERSIONINFOEXW, SZ_RTL_OSVERSIONINFOEXW);
CHKSZ(SLIST_HEADER, SZ_SLIST_HEADER);
CHKSZ(KLOCK_QUEUE_HANDLE, SZ_KLOCK_QUEUE_HANDLE);
CHKSZ(TIME_FIELDS, SZ_TIME_FIELDS);

CHKSZ(MDL, SZ_MDL);
CHK((MDL, MappedSystemVa), OFF_MDL_MAPPEDSYSTEMVA);
CHK((MDL, StartVa), OFF_MDL_STARTVA);
CHK((MDL, ByteCount), OFF_MDL_BYTECOUNT);
CHK((MDL, ByteOffset), OFF_MDL_BYTEOFFSET);

CHK((UNICODE_STRING, Buffer), OFF_USTR_BUFFER);
CHK((KDPC, DeferredRoutine), OFF_KDPC_DEFERREDROUTINE);
CHK((KDPC, DeferredContext), OFF_KDPC_DEFERREDCONTEXT);
CHK((KEVENT, Header.SignalState), OFF_KEVENT_SIGNALSTATE);

int ntddk_abi_ok;
