# SPDX-License-Identifier: GPL-2.0-only
"""VS_VERSIONINFO resources for the images the Win64 build produces (build.py, wineport/build.py).

Every DLL and EXE this tree builds carries a version resource, as every Microsoft-shipped image does: programs read module
versions (Chromium's crashpad records them for each loaded module; base::win::OSInfo reads kernel32.dll's file version
to confirm the Windows version), and version.dll's GetFileVersionInfo*W fails with ERROR_RESOURCE_DATA_NOT_FOUND on an
image without one. The resource is an ordinary .rc compiled by mingw windres: `-O coff` for GNU ld links, `-O res` for
lld-link (which takes .res files, not COFF .rsrc objects).

The file version is the OS version the Kernel64 loader writes into every PEB (kernel64/ldr.c: OSMajorVersion 10,
OSMinorVersion 0, OSBuildNumber 22631), with 1 as the private part, so the version a program derives from kernel32.dll
agrees with what RtlGetVersion/GetVersionEx report.

ProductVersion identifies the ShizukuOS 1.0.0 target independently of that
compatibility FileVersion. FILEFLAGS marks these development builds prerelease;
it does not certify the final release or actual Windows 98 app acceptance.
"""
import shutil
import subprocess
from pathlib import Path

WINDRES = "x86_64-w64-mingw32-windres"
OS_VERSION = (10, 0, 22631, 1)
PRODUCT_VERSION = (1, 0, 0, 0)
COMPANY = "The Shizuku Authors"
PRODUCT = "ShizukuOS development Win64 runtime"
VFT_APP, VFT_DLL = 1, 2


def rc_text(filename, description, filetype, version=OS_VERSION, product_version=None, internal_name=None):
    """The .rc source of one VERSIONINFO (language 0x0409, code page 1200)."""
    product_version = product_version or PRODUCT_VERSION
    internal_name = internal_name or filename.rsplit(".", 1)[0]
    v = ",".join(str(x) for x in version)
    pv = ",".join(str(x) for x in product_version)
    vs = ".".join(str(x) for x in version)
    pvs = ".".join(str(x) for x in product_version)
    return f"""/* generated by shizukudos/win64/tools/verres.py: version resource of {filename}. Do not edit. */
1 VERSIONINFO
 FILEVERSION {v}
 PRODUCTVERSION {pv}
 FILEFLAGSMASK 0x3fL
 FILEFLAGS 0x2L
 FILEOS 0x40004L
 FILETYPE {filetype:#x}L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "{COMPANY}"
            VALUE "FileDescription", "{description}"
            VALUE "FileVersion", "{vs}"
            VALUE "InternalName", "{internal_name}"
            VALUE "LegalCopyright", "Copyright (C) The Shizuku Authors. GPL-2.0-only."
            VALUE "OriginalFilename", "{filename}"
            VALUE "ProductName", "{PRODUCT}"
            VALUE "ProductVersion", "{pvs}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 0x04b0
    END
END
"""


def compile_version(out_dir, filename, description, filetype, fmt="coff", extra_rc=None, includes=(), **kw):
    """Writes <out_dir>/<stem>_ver.rc and compiles it to <stem>_ver.o (fmt "coff", for ld) or <stem>_ver.res (fmt "res",
    for lld-link). extra_rc: an existing resource script of the image to compile into the same object (an image gets one
    .rsrc from one object, so a program's own resources and the version block are compiled together); when that script
    already defines a VERSIONINFO the generated block is left out and only the script is compiled."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = filename.rsplit(".", 1)[0].lower()
    rc = out_dir / f"{stem}_ver.rc"
    obj = out_dir / (f"{stem}_ver.o" if fmt == "coff" else f"{stem}_ver.res")
    text = ""
    if extra_rc is not None:
        extra_rc = Path(extra_rc)
        text += f'#include "{extra_rc.resolve().as_posix()}"\n'
        includes = [*includes, extra_rc.parent]
        if "VERSIONINFO" in extra_rc.read_text():
            deps = [extra_rc]
            if obj.exists() and rc.exists() and rc.read_text() == text and all(d.stat().st_mtime <= obj.stat().st_mtime for d in deps):
                return obj
            rc.write_text(text)
            _windres(rc, obj, fmt, includes)
            return obj
    text += rc_text(filename, description, filetype, **kw)
    if obj.exists() and rc.exists() and rc.read_text() == text and (extra_rc is None or extra_rc.stat().st_mtime <= obj.stat().st_mtime):
        return obj
    rc.write_text(text)
    _windres(rc, obj, fmt, includes)
    return obj


def _windres(rc, obj, fmt, includes):
    if not shutil.which(WINDRES):
        raise SystemExit(f"required tool missing: {WINDRES}")
    cmd = [WINDRES, "-O", fmt, *[x for i in includes for x in ("-I", str(i))], "-o", str(obj), str(rc)]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise SystemExit(f"windres failed for {rc}: {r.stderr}")
