#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Writes stress-subset.txt: a reproducible sample of JavaScriptCore's JSTests/stress for tests/run_k64_webkit.py stress.
Selection (no hand picking): files under 1500 bytes that need nothing beyond a plain `jsc file.js` run, i.e. no `//@`
run directive (those select special options or skip platforms), no $vm/$262 test hooks, no GC/JIT-tier hooks, no
load()/readFile(), no WebAssembly or workers; then every k-th file of the sorted list so that N files remain."""
import re
import sys
from pathlib import Path

EXCLUDE = re.compile(r"\$vm|//@|\bload\(|\$262|Worker|\bgc\(|fullGC|edenGC|drainMicrotasks|noInline|numberOf\w*Compiles|"
                     r"wasm|WebAssembly|readFile|setTimeout|callerSourceOrigin|optimizeNextInvocation|OSRExit|ensureArrayStorage")


def select(stress_dir, n=60):
    ok = [p for p in sorted(Path(stress_dir).glob("*.js"))
          if p.stat().st_size < 1500 and not EXCLUDE.search(p.read_text(errors="replace"))]
    step = max(1, len(ok) // n)
    return ok[::step][:n], len(ok)


if __name__ == "__main__":
    tree = Path(sys.argv[1] if len(sys.argv) > 1 else "build/upstream/webkit")
    picked, eligible = select(tree / "JSTests" / "stress")
    out = Path(__file__).with_name("stress-subset.txt")
    out.write_text(f"# generated by gen_stress_subset.py from the pinned webkit tree: {len(picked)} of {eligible} eligible files\n" +
                   "".join(f"JSTests/stress/{p.name}\n" for p in picked))
    print(out, len(picked), eligible)
