#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Build the Shizuku Win64 user-mode runtime and test applications with mingw-w64, and pack
them into the Kernel64 initial RAM archive (WIN64.IMG).

Outputs (build/shizukudos/win64/): ntdll.dll, kernel32.dll (+ import libraries generated from
their export lists), the test executables, WIN64.IMG and build-result.json.

Export lists are generated from the sources: every function defined with NTAPI in ntdll and
every K32API function in kernel32 is exported, so an API exists exactly when it has a body.
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import shzlib  # noqa: E402
from shzlib import BUILD, REPO, SHZ, run, sha256_file  # noqa: E402

W64 = SHZ / "win64"
OUT = BUILD / "win64"
CC = "x86_64-w64-mingw32-gcc"
DLLTOOL = "x86_64-w64-mingw32-dlltool"
WINDRES = "x86_64-w64-mingw32-windres"
NTSYS = SHZ / "kernel64" / "ntsys.h"

COMMON = ["-O2", "-Wall", "-Wextra", "-Werror", "-ffreestanding", "-fno-builtin", "-fno-stack-protector",
          "-mno-red-zone", "-fno-ident", "-fno-tree-loop-distribute-patterns",
          "-Wno-unused-function", "-Wno-unused-parameter", "-Wno-cast-function-type"]
NTDLL_BASE = "0x7ffb00000000"
K32_BASE = "0x7ffb10000000"


def syscall_list():
    text = NTSYS.read_text()
    block = text[text.index("#define SYSCALL_LIST(X)"):text.index("enum {")]
    return [(m.group(1), int(m.group(2), 16)) for m in re.finditer(r"X\((\w+), (0x[0-9a-fA-F]+)\)", block)]


def gen_stubs():
    """One `mov r10, rcx; mov eax, N; syscall; ret` stub per system call (Windows x64 convention)."""
    lines = ["# Generated by shizukudos/win64/build.py from kernel64/ntsys.h. Do not edit.", "    .text"]
    exports = []
    for name, num in syscall_list():
        lines += [f"    .globl {name}", f"    .def {name}; .scl 2; .type 32; .endef", f"{name}:",
                  "    movq %rcx, %r10", f"    movl ${num}, %eax", "    syscall", "    ret"]
        exports.append(name)
        exports.append(f"Zw{name[2:]} = {name}")
    (OUT / "nt_stubs.S").write_text("\n".join(lines) + "\n")
    return exports


EXPORT_PATTERNS = {
    # SHZ_EXPORT <type> NTAPI Name(   (the SHZ_EXPORT prefix is optional; NTAPI/__cdecl names the calling convention)
    "NTAPI": r"^(?:SHZ_EXPORT\s+)?[A-Za-z_][\w\s\*]*?\b(?:NTAPI|__cdecl)\s+\**(\w+)\s*\(",
    # K32API <type> WINAPI Name(      (the name is the last identifier before the parameter list)
    "K32API": r"^K32API\s[^;{()]*?\b(\w+)\s*\(",
    # DLLAPI <type> WINAPI Name(      (extra modules under win64/dlls/<name>/)
    "DLLAPI": r"^DLLAPI\s[^;{()]*?\b(\w+)\s*\(",
}


def scan_exports(paths, marker):
    names = []
    for path in paths:
        text = path.read_text()
        names += [m.group(1) for m in re.finditer(EXPORT_PATTERNS[marker], text, re.M)]
    return sorted(set(names))


def write_def(path, library, names, forwarders=()):
    body = [f"LIBRARY {library}", "EXPORTS"]
    body += [f"  {n}" for n in names]
    body += [f"  {f}" for f in forwarders]
    path.write_text("\n".join(body) + "\n")


def build_ntdll():
    src = sorted((W64 / "ntdll").glob("*.c"))
    stub_exports = gen_stubs()
    names = scan_exports(src, "NTAPI")
    names = [n for n in names if n not in ("ShzInitSync",)]
    write_def(OUT / "ntdll.def", "ntdll.dll", names + ["RtlCaptureContext"] + stub_exports)
    dll = OUT / "ntdll.dll"
    cmd = [CC, *COMMON, "-DSHZ_NTDLL_BUILD", "-shared", "-nostdlib", "-Wl,--entry,ShzNtdllEntry",
           f"-Wl,--image-base,{NTDLL_BASE}", "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at",
           "-I", W64 / "include", *src, W64 / "ntdll" / "ntdll_asm.S", OUT / "nt_stubs.S", OUT / "ntdll.def",
           "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "ntdll.def", "-l", OUT / "libntdll.a", "--kill-at"])
    return dll, cmd, names


def build_kernel32(ntdll_names):
    src = sorted((W64 / "kernel32").glob("*.c"))
    names = scan_exports(src, "K32API")
    forwards = [f"{n} = ntdll.{n}" for n in ("RtlCaptureContext", "RtlLookupFunctionEntry", "RtlVirtualUnwind", "RtlUnwindEx",
                                                 "RtlUnwind", "RtlPcToFileHeader", "RtlRaiseException") if n in ntdll_names or n == "RtlCaptureContext"]
    names = [n for n in names if n not in ("RtlUnwindKernel32",)]
    write_def(OUT / "kernel32.def", "kernel32.dll", names, forwards)
    dll = OUT / "kernel32.dll"
    cmd = [CC, *COMMON, "-shared", "-nostdlib", "-Wl,--entry,ShzKernel32Entry", f"-Wl,--image-base,{K32_BASE}",
           "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at", "-I", W64 / "include", *src,
           OUT / "kernel32.def", "-L", OUT, "-lntdll", "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "kernel32.def", "-l", OUT / "libkernel32.a", "--kill-at"])
    return dll, cmd, names


DLL_BASE = 0x7ffb20000000
DLL_STRIDE = 0x01000000


def discover_modules():
    """Extra system DLLs: every win64/dlls/<name>/ containing *.c builds <name>.dll (+ lib<name>.a) and is packed as
    \\SHZ\\SYS64\\<name>.dll. Exported functions are the DLLAPI-marked definitions. Optional module.json:
    {"libs": ["advapi32"], "forwarders": ["Name = other.Name"]} lists other modules this one imports from."""
    root = W64 / "dlls"
    found = []
    for d in sorted(root.glob("*")) if root.is_dir() else []:
        if d.is_dir() and sorted(d.glob("*.c")):
            cfg = json.loads((d / "module.json").read_text()) if (d / "module.json").exists() else {}
            found.append((d.name, d, cfg))
    return found


def build_modules():
    pending = {name: (d, cfg) for name, d, cfg in discover_modules()}
    built, order = {}, []
    while pending:
        ready = [n for n, (d, cfg) in sorted(pending.items()) if all(l in built for l in cfg.get("libs", []) if l in pending or l in built)]
        if not ready:
            raise SystemExit(f"circular or missing module dependency among {sorted(pending)}")
        for name in ready:
            d, cfg = pending.pop(name)
            src = sorted(d.glob("*.c"))
            names = scan_exports(src, "DLLAPI")
            write_def(OUT / f"{name}.def", f"{name}.dll", names, cfg.get("forwarders", []))
            has_main = any(re.search(r"\bDllMain\s*\(", s.read_text()) for s in src)
            base = DLL_BASE + DLL_STRIDE * len(order)
            dll = OUT / f"{name}.dll"
            cmd = [CC, *COMMON, "-DBUILDING_" + name.upper(), "-shared", "-nostdlib", f"-Wl,--entry,{'DllMain' if has_main else '0'}",
                   f"-Wl,--image-base,{base:#x}", "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at",
                   "-I", W64 / "include", "-I", d, *src, OUT / f"{name}.def", "-L", OUT,
                   *[f"-l{l}" for l in ["kernel32", "ntdll", *cfg.get("libs", [])]], "-lgcc", "-o", dll]
            run(cmd)
            run([DLLTOOL, "-d", OUT / f"{name}.def", "-l", OUT / f"lib{name}.a", "--kill-at"])
            built[name] = {"dll": dll, "cmd": cmd, "exports": names, "base": base}
            order.append(name)
    return built


def build_apps(module_libs=()):
    apps = {}
    for src in sorted((W64 / "tests").glob("t_*.c")):
        name = src.stem
        exe = OUT / f"{name}.exe"
        extra = []
        rc = src.with_suffix(".rc")                       # optional resource script (e.g. a VERSIONINFO fixture)
        if rc.exists():
            res = OUT / f"{name}_res.o"
            run([WINDRES, "-O", "coff", "-o", res, rc])
            extra.append(res)
        crt = W64 / "crt"
        cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
               "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, src, crt / "shzcrt.c", *extra,
               "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
        run(cmd)
        apps[name] = (exe, cmd)
    return apps


def build_setup(module_libs=()):
    """SHZSETUP.EXE, the installer (win64/setup/*.c; its portable core is shared with the host tests in
    shizukudos/install/tests). Packed as \\SHZ\\SETUP\\SHZSETUP.EXE; Kernel64 runs it when booted with shz.setup=auto."""
    src = sorted((W64 / "setup").glob("*.c"))
    exe = OUT / "SHZSETUP.EXE"
    crt = W64 / "crt"
    cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
           "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, "-I", W64 / "setup", *src, crt / "shzcrt.c",
           "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
    run(cmd)
    return exe, cmd


def build_sys_apps(module_libs=()):
    """System programs: every win64/apps/<name>/ containing *.c builds <name>.exe, packed as \\SHZ\\SYS64\\<NAME>.EXE
    (not a T_*.EXE self-check: the kernel's test run does not start it)."""
    apps = {}
    root = W64 / "apps"
    for d in sorted(root.glob("*")) if root.is_dir() else []:
        src = sorted(d.glob("*.c"))
        if not d.is_dir() or not src:
            continue
        exe = OUT / f"{d.name}.exe"
        crt = W64 / "crt"
        cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
               "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, "-I", d, *src, crt / "shzcrt.c",
               "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
        run(cmd)
        apps[d.name] = (exe, cmd)
    return apps


def pack_archive(files):
    """SHZARC01: header, entries {char path[120]; u64 offset; u64 size}, then file data (16-byte aligned)."""
    entries = []
    blob = bytearray()
    header_size = 16 + 136 * len(files)
    for path, data in files:
        while (header_size + len(blob)) % 16:
            blob.append(0)
        entries.append((path, header_size + len(blob), len(data)))
        blob += data
    out = bytearray(b"SHZARC01" + struct.pack("<II", len(files), 0))
    for path, off, size in entries:
        raw = path.encode("ascii")
        assert len(raw) < 120
        out += raw.ljust(120, b"\0") + struct.pack("<QQ", off, size)
    return bytes(out + blob)


def main():
    argparse.ArgumentParser(description=__doc__).parse_args()
    for tool in (CC, DLLTOOL):
        if not shutil.which(tool):
            raise SystemExit(f"required tool missing: {tool}")
    OUT.mkdir(parents=True, exist_ok=True)
    ntdll, ntdll_cmd, ntdll_names = build_ntdll()
    k32, k32_cmd, k32_names = build_kernel32(ntdll_names)
    modules = build_modules()
    apps = build_apps(sorted(modules))
    setup_exe, _ = build_setup(sorted(modules))
    sys_apps = build_sys_apps(sorted(modules))
    files = [("\\SHZ\\SYS64\\ntdll.dll", ntdll.read_bytes()), ("\\SHZ\\SYS64\\kernel32.dll", k32.read_bytes())]
    for name, m in sorted(modules.items()):
        files.append((f"\\SHZ\\SYS64\\{name}.dll", m["dll"].read_bytes()))
    for name, (exe, _) in sorted(apps.items()):
        files.append((f"\\SHZ\\TESTS\\{exe.name.upper()}", exe.read_bytes()))
    files.append(("\\SHZ\\SETUP\\SHZSETUP.EXE", setup_exe.read_bytes()))
    for name, (exe, _) in sorted(sys_apps.items()):
        files.append((f"\\SHZ\\SYS64\\{exe.name.upper()}", exe.read_bytes()))
    data_dir = W64 / "tests" / "data"
    if data_dir.exists():
        for f in sorted(data_dir.iterdir()):
            files.append((f"\\SHZ\\TESTS\\{f.name.upper()}", f.read_bytes()))
    img = OUT / "WIN64.IMG"
    img.write_bytes(pack_archive(files))
    shutil.copy2(img, BUILD / "win64" / "WIN64.IMG") if False else None
    shzlib.write_json(OUT / "build-result.json", {
        "built_utc": shzlib.utc_now(), "git": shzlib.git_state(),
        "toolchain": {"mingw": shzlib.tool_version(CC)},
        "ntdll": {"sha256": sha256_file(ntdll), "exports": len(ntdll_names) + len(syscall_list()) * 2},
        "kernel32": {"sha256": sha256_file(k32), "exports": len(k32_names)},
        "modules": {n: {"sha256": sha256_file(m["dll"]), "exports": len(m["exports"]), "base": hex(m["base"])} for n, m in modules.items()},
        "apps": {n: sha256_file(e) for n, (e, _) in apps.items()},
        "setup": {"SHZSETUP.EXE": sha256_file(setup_exe)},
        "sys_apps": {n: sha256_file(e) for n, (e, _) in sys_apps.items()},
        "archive": {"sha256": sha256_file(img), "files": [p for p, _ in files]},
        "commands": {"ntdll": [str(x) for x in ntdll_cmd], "kernel32": [str(x) for x in k32_cmd]},
    })
    print(json.dumps({"ntdll_exports": len(ntdll_names), "kernel32_exports": len(k32_names), "modules": sorted(modules), "apps": sorted(apps),
                      "WIN64.IMG": sha256_file(img)}, indent=2))


if __name__ == "__main__":
    main()
