#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Build the Shizuku Win64 user-mode runtime and test applications with mingw-w64, and pack
them into the Kernel64 initial RAM archive (WIN64.IMG).

Outputs (build/shizukudos/win64/): ntdll.dll, kernel32.dll (+ import libraries generated from
their export lists), the test executables, WIN64.IMG and build-result.json.

Export lists are generated from the sources: every function defined with NTAPI in ntdll and
every K32API function in kernel32 is exported, so an API exists exactly when it has a body.
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import shzlib  # noqa: E402
from shzlib import BUILD, REPO, SHZ, run, sha256_file  # noqa: E402

W64 = SHZ / "win64"
OUT = BUILD / "win64"
CC = "x86_64-w64-mingw32-gcc"
DLLTOOL = "x86_64-w64-mingw32-dlltool"
WINDRES = "x86_64-w64-mingw32-windres"
NTSYS = SHZ / "kernel64" / "ntsys.h"

COMMON = ["-O2", "-Wall", "-Wextra", "-Werror", "-ffreestanding", "-fno-builtin", "-fno-stack-protector",
          "-mno-red-zone", "-fno-ident", "-fno-tree-loop-distribute-patterns",
          "-Wno-unused-function", "-Wno-unused-parameter", "-Wno-cast-function-type"]
NTDLL_BASE = "0x7ffb00000000"
K32_BASE = "0x7ffb10000000"


def syscall_list():
    text = NTSYS.read_text()
    block = text[text.index("#define SYSCALL_LIST(X)"):text.index("enum {")]
    return [(m.group(1), int(m.group(2), 16)) for m in re.finditer(r"X\((\w+), (0x[0-9a-fA-F]+)\)", block)]


def gen_stubs():
    """One `mov r10, rcx; mov eax, N; syscall; ret` stub per system call (Windows x64 convention)."""
    lines = ["# Generated by shizukudos/win64/build.py from kernel64/ntsys.h. Do not edit.", "    .text"]
    exports = []
    for name, num in syscall_list():
        lines += [f"    .globl {name}", f"    .def {name}; .scl 2; .type 32; .endef", f"{name}:",
                  "    movq %rcx, %r10", f"    movl ${num}, %eax", "    syscall", "    ret"]
        exports.append(name)
        exports.append(f"Zw{name[2:]} = {name}")
    (OUT / "nt_stubs.S").write_text("\n".join(lines) + "\n")
    return exports


EXPORT_PATTERNS = {
    # SHZ_EXPORT <type> NTAPI Name(   (the SHZ_EXPORT prefix is optional; NTAPI/__cdecl names the calling convention)
    "NTAPI": r"^(?:SHZ_EXPORT\s+)?[A-Za-z_][\w\s\*]*?\b(?:NTAPI|__cdecl)\s+\**(\w+)\s*\(",
    # K32API <type> WINAPI Name(      (the name is the last identifier before the parameter list)
    "K32API": r"^K32API\s[^;{()]*?\b(\w+)\s*\(",
}


def scan_exports(paths, marker):
    names = []
    for path in paths:
        text = path.read_text()
        names += [m.group(1) for m in re.finditer(EXPORT_PATTERNS[marker], text, re.M)]
    return sorted(set(names))


def write_def(path, library, names, forwarders=()):
    body = [f"LIBRARY {library}", "EXPORTS"]
    body += [f"  {n}" for n in names]
    body += [f"  {f}" for f in forwarders]
    path.write_text("\n".join(body) + "\n")


def build_ntdll():
    src = sorted((W64 / "ntdll").glob("*.c"))
    stub_exports = gen_stubs()
    names = scan_exports(src, "NTAPI")
    names = [n for n in names if n not in ("ShzInitSync",)]
    write_def(OUT / "ntdll.def", "ntdll.dll", names + ["RtlCaptureContext"] + stub_exports)
    dll = OUT / "ntdll.dll"
    cmd = [CC, *COMMON, "-DSHZ_NTDLL_BUILD", "-shared", "-nostdlib", "-Wl,--entry,ShzNtdllEntry",
           f"-Wl,--image-base,{NTDLL_BASE}", "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at",
           "-I", W64 / "include", *src, W64 / "ntdll" / "ntdll_asm.S", OUT / "nt_stubs.S", OUT / "ntdll.def",
           "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "ntdll.def", "-l", OUT / "libntdll.a", "--kill-at"])
    return dll, cmd, names


def build_kernel32(ntdll_names):
    src = sorted((W64 / "kernel32").glob("*.c"))
    names = scan_exports(src, "K32API")
    forwards = [f"{n} = ntdll.{n}" for n in ("RtlCaptureContext", "RtlLookupFunctionEntry", "RtlVirtualUnwind", "RtlUnwindEx",
                                                 "RtlUnwind", "RtlPcToFileHeader", "RtlRaiseException", "RtlCaptureStackBackTrace")
                if n in ntdll_names or n == "RtlCaptureContext"]
    names = [n for n in names if n not in ("RtlUnwindKernel32",)]
    write_def(OUT / "kernel32.def", "kernel32.dll", names, forwards)
    dll = OUT / "kernel32.dll"
    cmd = [CC, *COMMON, "-shared", "-nostdlib", "-Wl,--entry,ShzKernel32Entry", f"-Wl,--image-base,{K32_BASE}",
           "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at", "-I", W64 / "include", *src,
           OUT / "kernel32.def", "-L", OUT, "-lntdll", "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "kernel32.def", "-l", OUT / "libkernel32.a", "--kill-at"])
    return dll, cmd, names


def build_apps():
    apps = {}
    for src in sorted((W64 / "tests").glob("t_*.c")):
        name = src.stem
        exe = OUT / f"{name}.exe"
        extra = []
        rc = src.with_suffix(".rc")                 # optional resources for the program (tests/<name>.rc)
        if rc.exists():
            res = OUT / f"{name}_res.o"
            run([WINDRES, "-O", "coff", "-i", rc, "-o", res])
            extra.append(res)
        crt = W64 / "crt"
        cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
               "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, src, crt / "shzcrt.c", *extra,
               "-L", OUT, "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
        run(cmd)
        apps[name] = (exe, cmd)
    return apps


def pack_archive(files):
    """SHZARC01: header, entries {char path[120]; u64 offset; u64 size}, then file data (16-byte aligned)."""
    entries = []
    blob = bytearray()
    header_size = 16 + 136 * len(files)
    for path, data in files:
        while (header_size + len(blob)) % 16:
            blob.append(0)
        entries.append((path, header_size + len(blob), len(data)))
        blob += data
    out = bytearray(b"SHZARC01" + struct.pack("<II", len(files), 0))
    for path, off, size in entries:
        raw = path.encode("ascii")
        assert len(raw) < 120
        out += raw.ljust(120, b"\0") + struct.pack("<QQ", off, size)
    return bytes(out + blob)


def main():
    argparse.ArgumentParser(description=__doc__).parse_args()
    for tool in (CC, DLLTOOL, WINDRES):
        if not shutil.which(tool):
            raise SystemExit(f"required tool missing: {tool}")
    OUT.mkdir(parents=True, exist_ok=True)
    ntdll, ntdll_cmd, ntdll_names = build_ntdll()
    k32, k32_cmd, k32_names = build_kernel32(ntdll_names)
    apps = build_apps()
    files = [("\\SHZ\\SYS64\\ntdll.dll", ntdll.read_bytes()), ("\\SHZ\\SYS64\\kernel32.dll", k32.read_bytes())]
    for name, (exe, _) in sorted(apps.items()):
        files.append((f"\\SHZ\\TESTS\\{exe.name.upper()}", exe.read_bytes()))
    data_dir = W64 / "tests" / "data"
    if data_dir.exists():
        for f in sorted(data_dir.iterdir()):
            files.append((f"\\SHZ\\TESTS\\{f.name.upper()}", f.read_bytes()))
    img = OUT / "WIN64.IMG"
    img.write_bytes(pack_archive(files))
    shutil.copy2(img, BUILD / "win64" / "WIN64.IMG") if False else None
    shzlib.write_json(OUT / "build-result.json", {
        "built_utc": shzlib.utc_now(), "git": shzlib.git_state(),
        "toolchain": {"mingw": shzlib.tool_version(CC)},
        "ntdll": {"sha256": sha256_file(ntdll), "exports": len(ntdll_names) + len(syscall_list()) * 2},
        "kernel32": {"sha256": sha256_file(k32), "exports": len(k32_names)},
        "apps": {n: sha256_file(e) for n, (e, _) in apps.items()},
        "archive": {"sha256": sha256_file(img), "files": [p for p, _ in files]},
        "commands": {"ntdll": [str(x) for x in ntdll_cmd], "kernel32": [str(x) for x in k32_cmd]},
    })
    print(json.dumps({"ntdll_exports": len(ntdll_names), "kernel32_exports": len(k32_names), "apps": sorted(apps),
                      "WIN64.IMG": sha256_file(img)}, indent=2))


if __name__ == "__main__":
    main()
