#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Build the Shizuku Win64 user-mode runtime and test applications with mingw-w64, and pack
them into the Kernel64 initial RAM archive (WIN64.IMG).

Outputs (build/shizukudos/win64/): ntdll.dll, kernel32.dll (+ import libraries generated from
their export lists), the test executables, WIN64.IMG and build-result.json.

Export lists are generated from the sources: every function defined with NTAPI in ntdll and
every K32API function in kernel32 is exported, so an API exists exactly when it has a body.
"""
import argparse
import json
import re
import shutil
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import shzlib  # noqa: E402
from shzlib import BUILD, REPO, SHZ, run, sha256_file  # noqa: E402
sys.path.insert(0, str(Path(__file__).resolve().parent / "tools"))
import verres  # noqa: E402  (VS_VERSIONINFO resource of every built image)

W64 = SHZ / "win64"
OUT = BUILD / "win64"
CC = "x86_64-w64-mingw32-gcc"
DLLTOOL = "x86_64-w64-mingw32-dlltool"
WINDRES = "x86_64-w64-mingw32-windres"
NTSYS = SHZ / "kernel64" / "ntsys.h"

COMMON = ["-O2", "-Wall", "-Wextra", "-Werror", "-ffreestanding", "-fno-builtin", "-fno-stack-protector",
          "-mno-red-zone", "-fno-ident", "-fno-tree-loop-distribute-patterns",
          "-Wno-unused-function", "-Wno-unused-parameter", "-Wno-cast-function-type"]
NTDLL_BASE = "0x7ffb00000000"
K32_BASE = "0x7ffb10000000"
RES = OUT / "res"                       # generated version resources (tools/verres.py)


def version_obj(filename, description, filetype=verres.VFT_DLL, fmt="coff", extra_rc=None):
    """The compiled VS_VERSIONINFO of one image (every DLL and EXE gets one; see tools/verres.py)."""
    return verres.compile_version(RES, filename, description, filetype, fmt=fmt, extra_rc=extra_rc)


def syscall_list():
    text = NTSYS.read_text()
    block = text[text.index("#define SYSCALL_LIST(X)"):text.index("enum {")]
    return [(m.group(1), int(m.group(2), 16)) for m in re.finditer(r"X\((\w+), (0x[0-9a-fA-F]+)\)", block)]


def gen_stubs():
    """One `mov r10, rcx; mov eax, N; syscall; ret` stub per system call (Windows x64 convention)."""
    lines = ["# Generated by shizukudos/win64/build.py from kernel64/ntsys.h. Do not edit.", "    .text"]
    exports = []
    for name, num in syscall_list():
        lines += [f"    .globl {name}", f"    .def {name}; .scl 2; .type 32; .endef", f"{name}:",
                  "    movq %rcx, %r10", f"    movl ${num}, %eax", "    syscall", "    ret"]
        exports.append(name)
        exports.append(f"Zw{name[2:]} = {name}")
    (OUT / "nt_stubs.S").write_text("\n".join(lines) + "\n")
    return exports


EXPORT_PATTERNS = {
    # SHZ_EXPORT <type> NTAPI Name(   (the SHZ_EXPORT prefix is optional; NTAPI/__cdecl names the calling convention)
    "NTAPI": r"^(?:SHZ_EXPORT\s+)?[A-Za-z_][\w\s\*]*?\b(?:NTAPI|__cdecl)\s+\**(\w+)\s*\(",
    # K32API <type> WINAPI Name(      (the name is the last identifier before the parameter list)
    "K32API": r"^K32API\s[^;{()]*?\b(\w+)\s*\(",
    # DLLAPI <type> WINAPI Name(      (extra modules under win64/dlls/<name>/)
    "DLLAPI": r"^DLLAPI\s[^;{()]*?\b(\w+)\s*\(",
}


def scan_exports(paths, marker):
    names = []
    for path in paths:
        text = path.read_text()
        names += [m.group(1) for m in re.finditer(EXPORT_PATTERNS[marker], text, re.M)]
    return sorted(set(names))


def write_def(path, library, names, forwarders=(), ordinals=None):
    """ordinals: {name: ordinal} to pin (module.json "ordinals"): the Windows ordinals programs import by number (the
    Winsock 1.1 exports of ws2_32, for instance); every other export gets whatever ordinal the linker assigns."""
    ordinals = ordinals or {}
    missing = sorted(set(ordinals) - set(names))
    if missing:
        raise SystemExit(f"{library}: pinned ordinals for names that are not exported: {missing}")
    body = [f"LIBRARY {library}", "EXPORTS"]
    body += [f"  {n} @{ordinals[n]}" if n in ordinals else f"  {n}" for n in names]
    body += [f"  {f}" for f in forwarders]
    path.write_text("\n".join(body) + "\n")


def version_resource(rc):
    """Compiles a DLL's VERSIONINFO script (windres) and returns the object to link; programs read a system DLL's file
    version to learn the Windows build (Chromium base::win::OSInfo::Kernel32Version, crashpad's module list)."""
    res = OUT / (rc.stem + "_res.o")
    run([WINDRES, "-O", "coff", "-o", res, rc])
    return res


def build_ntdll():
    src = sorted((W64 / "ntdll").glob("*.c"))
    stub_exports = gen_stubs()
    names = scan_exports(src, "NTAPI")
    names = [n for n in names if n not in ("ShzInitSync",)]
    entries = names + ["RtlCaptureContext", "__C_specific_handler"] + stub_exports
    ordinal_file = W64 / "ntdll" / "ordinals.json"
    if ordinal_file.exists():
        policy = json.loads(ordinal_file.read_text())
        pins = policy.get("ordinals", {})
        actual_names = {entry.split("=", 1)[0].strip() for entry in entries}
        if (policy.get("library") != "ntdll.dll" or not isinstance(pins, dict) or set(pins) != actual_names
                or any(type(value) is not int or not 1 <= value <= 65535 for value in pins.values())
                or len(set(pins.values())) != len(pins)):
            raise SystemExit("ntdll.dll: exact named-export ordinal coverage and unique valid ordinals required")
        definitions = sorted({entry for entry in entries if "=" not in entry})
        aliases = sorted({entry for entry in entries if "=" in entry})
        for alias in aliases:
            name, target = (part.strip() for part in alias.split("=", 1))
            if target not in definitions:
                raise SystemExit(f"ntdll.dll: alias {name} has no actual local target {target}")
        alias_entries = [f"{entry} @{pins[entry.split('=', 1)[0].strip()]}" for entry in aliases]
        write_def(OUT / "ntdll.def", "ntdll.dll", definitions, alias_entries,
                  {name: pins[name] for name in definitions})
    else:
        write_def(OUT / "ntdll.def", "ntdll.dll", entries)
    dll = OUT / "ntdll.dll"
    cmd = [CC, *COMMON, "-DSHZ_NTDLL_BUILD", "-shared", "-nostdlib", "-Wl,--entry,ShzNtdllEntry",
           f"-Wl,--image-base,{NTDLL_BASE}", "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at",
           "-I", W64 / "include", *src, W64 / "ntdll" / "ntdll_asm.S", OUT / "nt_stubs.S", OUT / "ntdll.def",
           version_obj("ntdll.dll", "NT Layer DLL"), "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "ntdll.def", "-l", OUT / "libntdll.a", "--kill-at"])
    return dll, cmd, names


def build_kernel32(ntdll_names):
    src = sorted((W64 / "kernel32").glob("*.c"))
    names = scan_exports(src, "K32API")
    forwards = [f"{n} = ntdll.{n}" for n in ("RtlCaptureContext", "RtlLookupFunctionEntry", "RtlVirtualUnwind", "RtlUnwindEx",
                                                 "RtlUnwind", "RtlPcToFileHeader", "RtlRaiseException", "RtlCaptureStackBackTrace",
                                                 "VerSetConditionMask")
                if n in ntdll_names or n == "RtlCaptureContext"]
    names = [n for n in names if n not in ("RtlUnwindKernel32",)]
    # Windows kernel32 forwards these to ntdll too (V8 and Chromium import them from kernel32); delay-load resolution is
    # the api-ms-win-core-delayload contract, hosted by kernel32 here (kernelbase on Windows).
    forwards += [f"{n} = ntdll.{t}" for n, t in (
        ("RtlAddFunctionTable", "RtlAddFunctionTable"), ("RtlDeleteFunctionTable", "RtlDeleteFunctionTable"),
        ("RtlInstallFunctionTableCallback", "RtlInstallFunctionTableCallback"), ("RtlRestoreContext", "RtlRestoreContext"),
        ("ResolveDelayLoadedAPI", "LdrResolveDelayLoadedAPI"), ("ResolveDelayLoadsFromDll", "LdrResolveDelayLoadsFromDll"))
        if t in ntdll_names]
    write_def(OUT / "kernel32.def", "kernel32.dll", names, forwards)
    dll = OUT / "kernel32.dll"
    cmd = [CC, *COMMON, "-shared", "-nostdlib", "-Wl,--entry,ShzKernel32Entry", f"-Wl,--image-base,{K32_BASE}",
           "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at", "-I", W64 / "include", *src,
           OUT / "kernel32.def", version_obj("kernel32.dll", "Windows NT BASE API Client DLL"), "-L", OUT, "-lntdll", "-lgcc", "-o", dll]
    run(cmd)
    run([DLLTOOL, "-d", OUT / "kernel32.def", "-l", OUT / "libkernel32.a", "--kill-at"])
    return dll, cmd, names


DLL_BASE = 0x7ffb20000000
DLL_STRIDE = 0x01000000


def discover_modules():
    """Extra system DLLs: every win64/dlls/<name>/ containing *.c builds <name>.dll (+ lib<name>.a) and is packed as
    \\SHZ\\SYS64\\<name>.dll. Exported functions are the DLLAPI-marked definitions. Optional module.json:
    {"libs": ["advapi32"], "forwarders": ["Name = other.Name"], "description": "..."} lists other modules this one imports
    from; "description" is the FileDescription of its version resource (default: "<name>.dll")."""
    root = W64 / "dlls"
    found = []
    for d in sorted(root.glob("*")) if root.is_dir() else []:
        if d.is_dir() and sorted(d.glob("*.c")):
            cfg = json.loads((d / "module.json").read_text()) if (d / "module.json").exists() else {}
            found.append((d.name, d, cfg))
    return found


def build_modules():
    pending = {name: (d, cfg) for name, d, cfg in discover_modules()}
    built, order = {}, []
    while pending:
        ready = [n for n, (d, cfg) in sorted(pending.items()) if all(l in built for l in cfg.get("libs", []) if l in pending or l in built)]
        if not ready:
            raise SystemExit(f"circular or missing module dependency among {sorted(pending)}")
        for name in ready:
            d, cfg = pending.pop(name)
            src = sorted(d.glob("*.c"))
            names = scan_exports(src, "DLLAPI")
            write_def(OUT / f"{name}.def", f"{name}.dll", names, cfg.get("forwarders", []), cfg.get("ordinals"))
            has_main = any(re.search(r"\bDllMain\s*\(", s.read_text()) for s in src)
            base = DLL_BASE + DLL_STRIDE * len(order)
            dll = OUT / f"{name}.dll"
            cmd = [CC, *COMMON, "-DBUILDING_" + name.upper(), "-shared", "-nostdlib", f"-Wl,--entry,{'DllMain' if has_main else '0'}",
                   f"-Wl,--image-base,{base:#x}", "-Wl,--dynamicbase", "-Wl,--subsystem,console", "-Wl,--kill-at",
                   "-I", W64 / "include", "-I", d, *src, OUT / f"{name}.def",
                   version_obj(f"{name}.dll", cfg.get("description", f"{name}.dll")), "-L", OUT,
                   *[f"-l{l}" for l in ["kernel32", "ntdll", *cfg.get("libs", [])]], "-lgcc", "-o", dll]
            run(cmd)
            run([DLLTOOL, "-d", OUT / f"{name}.def", "-l", OUT / f"lib{name}.a", "--kill-at"])
            run([DLLTOOL, "-d", OUT / f"{name}.def", "-y", OUT / f"lib{name}_delay.a", "--kill-at"])  # delay-import lib
            built[name] = {"dll": dll, "cmd": cmd, "exports": names, "base": base}
            order.append(name)
    return built


# The runners check that T_HELLO.EXE sees its preferred base 0x140000000, so it is linked without DYNAMIC_BASE (a fixed
# image); T_LAZY.EXE is fixed at 0x140000000 too, so D:\LAZY\BIGRELOC.DLL (same preferred base) must be relocated.
# Every other app is relocatable and receives an ASLR base from the Kernel64 loader.
FIXED_BASE_APPS = {"t_hello", "t_lazy"}

# Apps that link a module through its DELAY-import library instead of its ordinary import library: the functions are
# resolved lazily on first call (dlltool --output-delaylib + crt/shzcrt.c __delayLoadHelper2 -> ResolveDelayLoadedAPI).
DELAY_MODULES = {"t_delay": ("winmm", "version")}


def build_apps(module_libs=()):
    apps = {}
    for src in sorted((W64 / "tests").glob("t_*.c")):
        name = src.stem
        exe = OUT / f"{name}.exe"
        rc = src.with_suffix(".rc")                       # optional resource script (e.g. a VERSIONINFO fixture)
        extra = [version_obj(f"{name}.exe", f"Shizuku Win64 self-check {name}", verres.VFT_APP, extra_rc=rc if rc.exists() else None)]
        crt = W64 / "crt"
        delayed = DELAY_MODULES.get(name, ())
        libs = [(f"{l}_delay" if l in delayed else l) for l in module_libs]
        cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
               "-Wl,--image-base,0x140000000", *(["-Wl,--disable-dynamicbase"] if name in FIXED_BASE_APPS else []),
               "-I", W64 / "include", "-I", crt, src, crt / "shzcrt.c", *extra,
               "-L", OUT, *[f"-l{l}" for l in libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
        run(cmd)
        apps[name] = (exe, cmd)
    return apps


def build_setup(module_libs=()):
    """SHZSETUP.EXE, the installer (win64/setup/*.c; its portable core is shared with the host tests in
    shizukudos/install/tests). Packed as \\SHZ\\SETUP\\SHZSETUP.EXE; Kernel64 runs it when booted with shz.setup=auto."""
    src = sorted((W64 / "setup").glob("*.c"))
    exe = OUT / "SHZSETUP.EXE"
    crt = W64 / "crt"
    cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
           "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, "-I", W64 / "setup", *src, crt / "shzcrt.c",
           version_obj("SHZSETUP.EXE", "ShizukuDOS 10 Setup", verres.VFT_APP),
           "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
    run(cmd)
    return exe, cmd


def build_sys_apps(module_libs=()):
    """System programs: every win64/apps/<name>/ containing *.c builds <name>.exe, packed as \\SHZ\\SYS64\\<NAME>.EXE
    (not a T_*.EXE self-check: the kernel's test run does not start it)."""
    apps = {}
    root = W64 / "apps"
    for d in sorted(root.glob("*")) if root.is_dir() else []:
        src = sorted(d.glob("*.c"))
        if not d.is_dir() or not src:
            continue
        exe = OUT / f"{d.name}.exe"
        crt = W64 / "crt"
        cmd = [CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
               "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, "-I", d, *src, crt / "shzcrt.c",
               version_obj(f"{d.name}.exe", f"ShizukuDOS 10 {d.name}", verres.VFT_APP),
               "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe]
        run(cmd)
        apps[d.name] = (exe, cmd)
    return apps


CLANGXX = "clang++"
LLD_LINK = "lld-link"
CXX_FLAGS = ["--target=x86_64-pc-windows-msvc", "-std=c++20", "-O1", "-fms-extensions", "-fexceptions", "-fcxx-exceptions",
             "-fno-stack-protector", "-Wall", "-Wextra", "-Werror", "-Wno-unused-parameter"]


def build_cxx_apps(module_libs=()):
    """MSVC-ABI C++ tests (tests/t_*.cpp): clang++ -target x86_64-pc-windows-msvc emits Microsoft's x64 C++ exception
    tables (FH3) and runtime calls, and lld-link imports them from the Shizuku DLLs through their import libraries, so
    each executable has the shape of an MSVC-built one. Entry point: ShzCxxStart."""
    apps = {}
    srcs = sorted((W64 / "tests").glob("t_*.cpp"))
    if not srcs:
        return apps
    for tool in (CLANGXX, LLD_LINK):
        if not shutil.which(tool):
            raise SystemExit(f"required tool missing: {tool}")
    first = [m for m in ("vcruntime140", "vcruntime140_1", "msvcp140", "ucrtbase") if m in module_libs]
    libs = [*first, *[m for m in module_libs if m not in first], "kernel32", "ntdll"]     # the CRT resolves first, as with MSVC
    for src in srcs:
        name = src.stem
        obj, exe = OUT / f"{name}.obj", OUT / f"{name}.exe"
        run([CLANGXX, *CXX_FLAGS, "-c", src, "-o", obj])
        cmd = [LLD_LINK, "/nologo", "/entry:ShzCxxStart", "/subsystem:console", "/nodefaultlib", "/base:0x140000000",
               f"/out:{exe}", obj, version_obj(f"{name}.exe", f"Shizuku Win64 self-check {name}", verres.VFT_APP, fmt="res"),
               *[OUT / f"lib{lib}.a" for lib in libs]]
        run(cmd)
        apps[name] = (exe, cmd)
    return apps


DDK_CANDIDATES = ["/usr/share/mingw-w64/include/ddk", "/usr/x86_64-w64-mingw32/include/ddk",
                  "/usr/x86_64-w64-mingw32/sys-root/mingw/include/ddk", "/usr/local/x86_64-w64-mingw32/include/ddk"]
DRV_FLAGS = ["-O2", "-Wall", "-Wextra", "-ffreestanding", "-fno-builtin", "-fno-stack-protector", "-mno-red-zone",
             "-fno-ident", "-fno-asynchronous-unwind-tables", "-D_WIN64"]


def find_ddk():
    for c in DDK_CANDIDATES:
        if (Path(c) / "wdm.h").exists():
            return c
    raise SystemExit("mingw-w64 DDK headers (ddk/wdm.h) not found; install mingw-w64 with the DDK headers")


def build_ntdrv_host():
    """Build the NT-driver-host artifacts: the ABI cross-check (fails the build on any offset drift),
    the ntoskrnl.exe/hal.dll export tables + import libraries, and the unmodified test .sys drivers."""
    ddk = find_ddk()
    ntdir = OUT / "ntdrv"
    ntdir.mkdir(parents=True, exist_ok=True)
    # 1. Prove kernel64/ntddk.h matches Microsoft's wdm.h (compile-only; a mismatch is a failed _Static_assert).
    run([CC, "-fsyntax-only", "-D_WIN64", "-I", ddk, "-I", SHZ / "kernel64", W64 / "tools" / "ntddk_abi_check.c"])
    # 2. Emit the export surface from kernel64/ntdrv_prov.c and make import libraries whose LIBRARY names are the DLLs.
    run([sys.executable, str(W64 / "tools" / "gen_ntoskrnl_exports.py"), "--out", str(ntdir)])
    run([DLLTOOL, "-d", ntdir / "ntoskrnl.def", "-l", ntdir / "libntoskrnl.a"])
    run([DLLTOOL, "-d", ntdir / "hal.def", "-l", ntdir / "libhal.a"])
    exports = json.loads((ntdir / "ntoskrnl-exports.json").read_text())
    drivers = {}
    for src in sorted((W64 / "drivers").glob("*.c")):
        name = src.stem
        obj, sysf = ntdir / (name + ".o"), ntdir / (name + ".sys")
        run([CC, *DRV_FLAGS, "-I", ddk, "-c", src, "-o", obj])
        run([CC, "-shared", "-nostdlib", "-Wl,--subsystem,native", "-Wl,--entry,DriverEntry",
             "-Wl,--image-base,0x1c0000000", "-Wl,--dynamicbase", "-Wl,--kill-at",
             "-o", sysf, obj, "-L", ntdir, "-lntoskrnl", "-lhal", "-lgcc"])
        drivers[name] = sysf
    return ntdir, drivers, exports


def build_ntdrv_app(module_libs, name="t_ntdrv"):
    """win64/ntdrv/<name>.c: a driver-host test program that is not packed into WIN64.IMG (t_ntdrv -> WIN64_NTDRV.IMG;
    t_drv_pnp -> the initrd tests/run_k64_pnp.py composes with the corpus driver store)."""
    crt = W64 / "crt"
    src = W64 / "ntdrv" / f"{name}.c"
    exe = OUT / f"{name}.exe"
    run([CC, *COMMON, "-nostdlib", "-Wl,--entry,ShzStart", "-Wl,--subsystem,console", "-Wl,--kill-at",
         "-Wl,--image-base,0x140000000", "-I", W64 / "include", "-I", crt, src, crt / "shzcrt.c",
         version_obj(f"{name}.exe", f"Shizuku Win64 self-check {name}", verres.VFT_APP),
         "-L", OUT, *[f"-l{l}" for l in module_libs], "-lkernel32", "-lntdll", "-lgcc", "-o", exe])
    return exe


def pack_archive(files):
    """SHZARC01: header, entries {char path[120]; u64 offset; u64 size}, then file data (16-byte aligned)."""
    entries = []
    blob = bytearray()
    header_size = 16 + 136 * len(files)
    for path, data in files:
        while (header_size + len(blob)) % 16:
            blob.append(0)
        entries.append((path, header_size + len(blob), len(data)))
        blob += data
    out = bytearray(b"SHZARC01" + struct.pack("<II", len(files), 0))
    for path, off, size in entries:
        raw = path.encode("ascii")
        assert len(raw) < 120
        out += raw.ljust(120, b"\0") + struct.pack("<QQ", off, size)
    return bytes(out + blob)


def build_wineport():
    """DLLs ported from the pinned Wine tree (wineport/build.py): list of (archive path, bytes) plus the result."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("wineport_build", W64 / "wineport" / "build.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    res = mod.build()
    files = list(res["files"])
    for name, t in sorted(res["tests"].items()):
        if t["in_plain_image"]:
            files.append((f"\\SHZ\\TESTS\\{t['exe'].name.upper()}", t["exe"].read_bytes()))
    return files, {n: {"exports": m["exports"], "counts": m["counts"]} for n, m in res["modules"].items()}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-wineport", action="store_true", help="do not build/pack the DLLs ported from Wine")
    args = ap.parse_args()
    for tool in (CC, DLLTOOL, WINDRES):
        if not shutil.which(tool):
            raise SystemExit(f"required tool missing: {tool}")
    OUT.mkdir(parents=True, exist_ok=True)
    ntdll, ntdll_cmd, ntdll_names = build_ntdll()
    k32, k32_cmd, k32_names = build_kernel32(ntdll_names)
    modules = build_modules()
    wine_files, wine_info = build_wineport() if not args.no_wineport else ([], {})
    apps = build_apps(sorted(modules))
    setup_exe, _ = build_setup(sorted(modules))
    sys_apps = build_sys_apps(sorted(modules))
    apps.update(build_cxx_apps(sorted(modules)))
    files = [("\\SHZ\\SYS64\\ntdll.dll", ntdll.read_bytes()), ("\\SHZ\\SYS64\\kernel32.dll", k32.read_bytes())]
    for name, m in sorted(modules.items()):
        files.append((f"\\SHZ\\SYS64\\{name}.dll", m["dll"].read_bytes()))
    files += wine_files
    files += __import__("runpy").run_path(str(W64 / "trident" / "build.py"))["build"](OUT)  # W2 hook: ShizukuTrident (trident/)
    for name, (exe, _) in sorted(apps.items()):
        files.append((f"\\SHZ\\TESTS\\{exe.name.upper()}", exe.read_bytes()))
    files.append(("\\SHZ\\SETUP\\SHZSETUP.EXE", setup_exe.read_bytes()))
    for name, (exe, _) in sorted(sys_apps.items()):
        files.append((f"\\SHZ\\SYS64\\{exe.name.upper()}", exe.read_bytes()))
    data_dir = W64 / "tests" / "data"
    if data_dir.exists():
        for f in sorted(data_dir.iterdir()):
            files.append((f"\\SHZ\\TESTS\\{f.name.upper()}", f.read_bytes()))
    # NT driver host: a separate initrd carries the driver store (\SHZ\DRIVERS), so the default WIN64.IMG has none and
    # Kernel64's ntdrv_selftest() stays a no-op there. The unmodified ECHO.SYS test driver does ride in WIN64.IMG as test
    # data (\SHZ\TESTS\ECHO.SYS, not a driver store): T_DRV_LOAD.EXE packages it and takes it through
    # SHZPNP.EXE add-driver / load / status / unload, the path a vendor package uses.
    # tests/run_k64_ntdrv.py mounts the driver-store image.
    ntdir, drivers, nt_exports = build_ntdrv_host()
    ntapp = build_ntdrv_app(sorted(modules))
    pnpapp = build_ntdrv_app(sorted(modules), "t_drv_pnp")
    files.append(("\\SHZ\\TESTS\\ECHO.SYS", drivers["echo"].read_bytes()))
    img = OUT / "WIN64.IMG"
    img.write_bytes(pack_archive(files))

    ntfiles = [("\\SHZ\\SYS64\\ntdll.dll", ntdll.read_bytes()), ("\\SHZ\\SYS64\\kernel32.dll", k32.read_bytes())]
    for name, m in sorted(modules.items()):
        ntfiles.append((f"\\SHZ\\SYS64\\{name}.dll", m["dll"].read_bytes()))
    for name, sysf in sorted(drivers.items()):
        ntfiles.append((f"\\SHZ\\DRIVERS\\{name.upper()}.SYS", sysf.read_bytes()))
    ntfiles.append(("\\SHZ\\TESTS\\T_NTDRV.EXE", ntapp.read_bytes()))
    ntfiles.append(("\\SHZ\\TESTS\\T_HELLO.EXE", apps["t_hello"][0].read_bytes()))
    ntimg = OUT / "WIN64_NTDRV.IMG"
    ntimg.write_bytes(pack_archive(ntfiles))

    shzlib.write_json(OUT / "build-result.json", {
        "built_utc": shzlib.utc_now(), "git": shzlib.git_state(),
        "toolchain": {"mingw": shzlib.tool_version(CC)},
        "ntdll": {"sha256": sha256_file(ntdll), "exports": len(ntdll_names) + len(syscall_list()) * 2},
        "kernel32": {"sha256": sha256_file(k32), "exports": len(k32_names)},
        "modules": {n: {"sha256": sha256_file(m["dll"]), "exports": len(m["exports"]), "base": hex(m["base"])} for n, m in modules.items()},
        "apps": {n: sha256_file(e) for n, (e, _) in apps.items()},
        "wineport": wine_info,
        "setup": {"SHZSETUP.EXE": sha256_file(setup_exe)},
        "sys_apps": {n: sha256_file(e) for n, (e, _) in sys_apps.items()},
        "archive": {"sha256": sha256_file(img), "files": [p for p, _ in files]},
        "ntdrv": {
            "ntoskrnl_exports": len(nt_exports["ntoskrnl.exe"]), "hal_exports": len(nt_exports["hal.dll"]),
            "drivers": {n: sha256_file(s) for n, s in sorted(drivers.items())},
            "app": sha256_file(ntapp), "archive": {"sha256": sha256_file(ntimg), "files": [p for p, _ in ntfiles]},
        },
        "commands": {"ntdll": [str(x) for x in ntdll_cmd], "kernel32": [str(x) for x in k32_cmd]},
    })
    print(json.dumps({"ntdll_exports": len(ntdll_names), "kernel32_exports": len(k32_names), "modules": sorted(modules), "apps": sorted(apps),
                      "WIN64.IMG": sha256_file(img),
                      "ntdrv": {"providers": len(nt_exports["ntoskrnl.exe"]) + len(nt_exports["hal.dll"]),
                                "drivers": sorted(drivers), "WIN64_NTDRV.IMG": sha256_file(ntimg),
                                "T_DRV_PNP.EXE": sha256_file(pnpapp)}}, indent=2))


if __name__ == "__main__":
    main()
