/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef M98_TLS13_PROTOCOL_CONFIG_H
#define M98_TLS13_PROTOCOL_CONFIG_H
#undef MBEDTLS_NET_C
#undef MBEDTLS_DEBUG_C
#undef MBEDTLS_FS_IO
#undef MBEDTLS_SSL_PROTO_TLS1_2
#undef MBEDTLS_SSL_PROTO_DTLS
#undef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_SSL_SESSION_TICKETS
#undef MBEDTLS_SSL_EARLY_DATA
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#endif
